---
- name: "Force APT to use IPv4 (avoid bad or slow IPv6 mirrors)"
  ansible.builtin.template:
    src: apt-force-ipv4
    dest: /etc/apt/apt.conf.d/99force-ipv4
    owner: root
    group: root
    mode: "0644"

# Needed to enable backport repository
- name: Install gnupg2
  ansible.builtin.apt:
    pkg: gnupg2
    state: present
    update_cache: true

- name: "Enable backport repository"
  ansible.builtin.apt_repository:
    repo: "deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main contrib non-free"
    filename: debian-backports
    state: present
  tags:
    - system
  # Don't run the task if the version is bullseye or older
  when: ansible_distribution_release not in ['bullseye', 'buster', 'stretch']

# TODO: this might not be useful as of today ;-)
- name: "Find python package prefix"
  ansible.builtin.set_fact:
    base__python_pkg_prefix: "python{% if ansible_python.version.major == 3 %}3{% endif %}"
  tags:
    - system

# TODO: do we need to install ansible everywhere ?
# TODO: move htop/iotop/screen install elsewhere
- name: "Install essential apt dependencies"
  ansible.builtin.apt:
    pkg:
      # apt tools
      - apt-transport-https
      - aptitude
      - unattended-upgrades
      # acl are useful also for ansible if we use become_user
      - acl
      # sys admin tools
      - lsb-release
      - etckeeper
      - molly-guard
      # network tools
      - curl
      - rsync
      - netcat-openbsd
      - net-tools
      # file tools
      - unzip
      # dev tools
      - git
      # security tools
      - dirmngr
      - sudo
      # perfs tools
      - htop
      - iotop
      # utilities
      - screen
      - vim
      # ansible
      - "{{ base__python_pkg_prefix }}-apt"
      - "{{ base__python_pkg_prefix }}-httplib2"
      - "{{ base__python_pkg_prefix }}-pip"
      - "{{ base__python_pkg_prefix }}-setuptools"
      - "{{ base__python_pkg_prefix }}-psycopg2"
      - ansible
    state: present
    update_cache: true
  tags:
    - system

- name: "Install APT auto-upgrades configuration"
  ansible.builtin.template:
    src: apt-auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: "0644"

- name: "Install unattended-upgrades configuration"
  ansible.builtin.template:
    src: apt-unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: "0644"
