---
- name: "Ensure no over-hardening prevent systemd-hostnamed.service to start (on Deb 11, full is OK, strict is KO)"
  ansible.builtin.lineinfile:
    path: /lib/systemd/system/systemd-hostnamed.service
    regexp: "^ProtectSystem="
    line: ProtectSystem=full
  when: ansible_facts['distribution'] == 'Debian' and ansible_facts['distribution_version'] >= '11'
  notify:
    - "Reload systemd"
    - "Restart systemd-hostnamed"
  tags:
    - host
    - system

- name: "Set server hostname"
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    use: systemd
  ignore_errors: true
  register: base__hostname_result
  failed_when: >
    base__hostname_result.failed and
    'read-only filesystem' not in base__hostname_result.msg and
    'Could not set pretty hostname' not in base__hostname_result.msg
  tags:
    - host

- name: "Warn about hostname change" # noqa:ignore-errors
  ansible.builtin.fail:
    msg: >
      WARNING: hostname not changed by previous task,
      if it is a VM, you must change the hostname from proxmox
  ignore_errors: true
  when: >
    base__hostname_result.failed and
    ('read-only filesystem' in base__hostname_result.msg) or
    ('Could not set pretty hostname' in base__hostname_result.msg)

- name: "Proper /etc/hosts reference to localhost"
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: "^127\\.0\\.0\\.1[\\s\\t]+"
    line: "127.0.0.1 {{ inventory_hostname }}.{{ host_domain }} {{ inventory_hostname }} localhost"
    state: present
  tags:
    - host

- name: "Proper /etc/hosts reference to FQDN"
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ansible_facts['default_ipv4'].address | regex_escape() }}[\\s\\t]+"
    line: "{{ ansible_facts['default_ipv4'].address }} {{ inventory_hostname }}.{{ host_domain }} {{ inventory_hostname }}"
    insertafter: "^127\\.0\\.0\\.1[\\s\\t]+"
    state: present
  tags:
    - host

- name: "Proper /etc/hosts ipv6 reference to FQDN"
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ansible_facts['default_ipv6'].address | regex_escape() }}[\\s\\t]+"
    line: "{{ ansible_facts['default_ipv6'].address }} {{ inventory_hostname }}.{{ host_domain }} {{ inventory_hostname }}"
    insertafter: "^127\\.0\\.0\\.1[\\s\\t]+"
    state: present
  when: "ansible_facts['default_ipv6'].address is defined"
  tags:
    - host

# remove reference to 127.0.1.1 added by debian,
# which is not the same as 127.0.0.1
- name: "No /etc/hosts reference to 127.0.1.1"
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: "^127\\.0\\.1\\.1[\\s\\t]+"
    state: absent
  tags:
    - host

- name: "Set ansible_fqdn fact"
  ansible.builtin.set_fact:
    ansible_fqdn: "{{ inventory_hostname }}.{{ host_domain }}" # noqa: var-naming
