---
- name: "Ensure no over-hardening prevent systemd-logind.service to start (on Deb 11, full is OK, strict is KO)"
  ansible.builtin.lineinfile:
    path: /lib/systemd/system/systemd-logind.service
    regexp: "^ProtectSystem="
    line: ProtectSystem=full
  when: ansible_facts['distribution'] == 'Debian' and ansible_facts['distribution_version'] >= '11'
  notify:
    - "Reload systemd"
    - "Restart systemd-logind"
  tags:
    - login
    - system
