---
- name: "Import tasks from login.yml"
  ansible.builtin.import_tasks: login.yml
  tags: login

- name: "Import tasks from hostname.yml"
  ansible.builtin.import_tasks: hostname.yml
  tags: hostname

- name: "Import tasks from apt.yml"
  ansible.builtin.import_tasks: apt.yml
  tags: apt

- name: "Import tasks from time.yml"
  ansible.builtin.import_tasks: time.yml
  tags: time

- name: "Import tasks from motd.yml"
  ansible.builtin.import_tasks: motd.yml
  tags: motd

# enables having terminal color and so on…
- name: "Ensure root bashrc is uptodate"
  ansible.builtin.copy:
    src: "/etc/skel/.bashrc"
    dest: "/root/.bashrc"
    mode: "0644"
    owner: root
    group: root
    remote_src: true
  tags: skel_files
