---
proxmox_node__pve_cluster_addr0: 10.12.0.3

proxmox_node__zfs_pools:
  - name: rpool
    vdev: raidz1 nvme0n1p5 nvme1n1p5
    properties:
      ashift: "12"
    filesystem_properties: "{{ proxmox_node__zfs_pools_filesystem_properties_defaults }}"

proxmox_node__zfs_filesystems:
  - name: rpool/pve
  - name: rpool/backups
  - name: rpool/virtiofs
    properties:
      # this is mandatory for virtiofs to work well in linux
      acltype: posixacl
  - name: rpool/virtiofs/qm-202
  - name: rpool/virtiofs/qm-202/docker-volumes
  # data of off-query postgres replication
  - name: rpool/virtiofs/qm-202/docker-volumes/off-query-replica_dbdata

proxmox_node__pve_storages:
  - name: rpool-pve
    type: zfspool
    pool: rpool/pve
    content: rootdir,images
    mountpoint: /rpool/pve
    sparse: 0
    shared: 0
  - name: local
    type: dir
    path: /var/lib/vz
    content: vztmpl,snippets,iso
    shared: 0

proxmox_node__partitions:
  - name: nvme0n1p5
    device: /dev/nvme0n1
    state: present
    fs_type: zfs
    flags: []
    label: "gpt"
    number: 5
    part_start: 273942528KiB
    part_end: "100%"
    part_type: primary
  - name: nvme1n1p5
    device: /dev/nvme1n1
    state: present
    fs_type: zfs
    flags: []
    label: "gpt"
    number: 5
    part_start: 273942528KiB
    part_end: "100%"
    part_type: primary
