# Stunnel configuration for off services
# /usr/share/doc/stunnel4/examples/stunnel.conf-sample

# we need this to run it smoothly with systemd
foreground = yes
# drop root
setuid = stunnel4
setgid = stunnel4
pid = /tmp/stunnel.pid
debug = warning

# enabling connections to Robotoff API from OVH1 reverse proxy
[Robotoff]
client = no
# we listen to ipv6 address
accept = :::16000
connect = 10.3.0.200:5500
ciphers = PSK
# this file and directory are private
PSKsecrets = /etc/stunnel/psk/robotoff-psk.txt

# enabling connections to off-query from off
[off-query]
client = no
# we listen to ipv6 address
accept = :::16001
connect = 10.3.0.200:5511
ciphers = PSK
# this file and directory are private
PSKsecrets = /etc/stunnel/psk/off-query-psk.txt

[Triton-gRPC]
client = no
accept = :::5504
connect = 10.3.0.200:5504
ciphers = PSK
PSKsecrets = /etc/stunnel/psk/triton-psk.txt

[Triton-HTTP]
client = no
accept = :::5503
connect = 10.3.0.200:5503
ciphers = PSK
PSKsecrets = /etc/stunnel/psk/triton-psk.txt

# Allow access from OVH1 reverse proxy
[Triton-GPU-gRPC]
client = no
accept = :::5507
connect = 10.3.0.201:5504
ciphers = PSK
PSKsecrets = /etc/stunnel/psk/triton-psk.txt

[Triton-GPU-HTTP]
client = no
accept = :::5506
connect = 10.3.0.201:5503
ciphers = PSK
PSKsecrets = /etc/stunnel/psk/triton-psk.txt
