---
- name: Find /etc/pve files
  ansible.builtin.find:
    paths: "{{ pull_pve_configs__source_dir }}"
    file_type: file
    recurse: true
  register: pull_pve_configs__files

- name: Fetch /etc/pve files
  ansible.builtin.fetch:
    src: "{{ item.path }}"
    dest: "{{ pull_pve_configs__pulled_confs_root }}"
  loop: "{{ pull_pve_configs__files.files }}"
