proxmox_node__pve_cluster_addr0: 10.12.0.1

proxmox_node_zfs_pools:
  - name: hdd-zfs
    # we use full dev name for nvme because it seems they switch between boot
    vdev: raidz1 sda5 sdb5 sdc5 sdd5 cache nvme-SAMSUNG_MZVL21T0HCLR-00B00_S676NF0WB06046-part1 nvme-SAMSUNG_MZVL21T0HCLR-00B00_S676NF0WB06047-part1
    properties:
      ashift: "12"
    filesystem_properties: "{{ proxmox_node_zfs_pools_filesystem_properties_defaults }}"

proxmox_node_zfs_filesystems:
  - name: hdd-zfs/pve
  - name: hdd-zfs/backups

proxmox_node__pve_storages:
  - name: hdd-zfs-pve
    type: zfspool
    pool: hdd-zfs/pve
    content: rootdir,images
    mountpoint: /hdd-zfs/pve
    sparse: 0
    shared: 0
  - name: local
    type: dir
    path: /var/lib/vz
    content: vztmpl,snippets,iso
    shared: 0
  # removing installed storage
  - name: hdd-zfs
    type: zfspool
    pool: hdd-zfs
    state: absent
