---
sanoid__datasets_to_create:
  - hdd-zfs/off-backups
  - hdd-zfs/off-backups/ovh3-rpool
  - hdd-zfs/off-backups/monitoring-01-hdd-zfs
  - hdd-zfs/off-backups/monitoring-01-data-zfs

sanoid__create_operators:
  - username: hetzner01operator
    server: ovh3
    server_fqdn: ovh3.openfoodfacts.org
    # because of backup dataset
    needs_sync_snap: true
  - username: hetzner01operator
    server: monitoring-01
    server_fqdn: monitoring-01.openfoodfacts.org
    needs_sync_snap: false
  - username: hetzner01operator
    server: hetzner-02
    server_fqdn: hetzner-02.openfoodfacts.org
    needs_sync_snap: false
  - username: hetzner01operator
    server: hetzner-03
    server_fqdn: hetzner-03.openfoodfacts.org
    needs_sync_snap: false
  - username: hetzner01operator
    server: scaleway-01
    server_fqdn: scaleway-01.infra.openfoodfacts.org
    needs_sync_snap: false
  - username: hetzner01operator
    server: scaleway-02
    server_fqdn: scaleway-02.infra.openfoodfacts.org
    needs_sync_snap: false
  - username: hetzner01operator
    server: scaleway-03
    server_fqdn: scaleway-03.infra.openfoodfacts.org
    needs_sync_snap: false
