# Stunnel configuration for off services
# /usr/share/doc/stunnel4/examples/stunnel.conf-sample

# we need this to run it smoothly with systemd
foreground = yes
# drop root
setuid = stunnel4
setgid = stunnel4

pid = /var/run/stunnel-off/stunnel.pid
# Can be emerg, alert, crit, err, warning, notice, info or debug
debug = err

# stunnel client is for client = yes service, the other should go to reverse-proxy

# Triton deployed on gpu-01
# Open Prices deployed on scaleway server need to access
# Triton
[Triton-HTTP]
client = yes
# BEWARE: as we have a public ipv6, only accept on private ipv4
accept = 10.13.1.101:5505
connect = 34.140.15.35:5506
ciphers = PSK
PSKsecrets = /etc/stunnel/psk/triton-psk.txt

[Triton-gRPC]
client = yes
# BEWARE: as we have a public ipv6, only accept on private ipv4
accept = 10.13.1.101:5504
connect = 34.140.15.35:5507
ciphers = PSK
PSKsecrets = /etc/stunnel/psk/triton-psk.txt

# off query at moji
[MojiOffQuery]
client = yes
# BEWARE: as we have a public ipv6, only accept on private ipv4
accept = 10.13.1.101:16001
connect = 2a06:c484:5::102:16001
ciphers = PSK
PSKsecrets = /etc/stunnel/psk/moji-off-query-psk.txt

# PaddleX is used by Open Prices to perform OCR
[Paddlex]
client = yes
# BEWARE: as we have a public ipv6, only accept on private ipv4
accept = 10.13.1.101:5610
# target: docker-prod-2 (osm45)
connect = 2a06:c484:5::102:5610
ciphers = PSK
PSKsecrets = /etc/stunnel/psk/paddlex-psk.txt
