---

_off_ansible_ssh_hosts_ips: |
  {{
    groups['all']
    | map('extract', hostvars)
    | map(attribute='ansible_ssh_host', default="")
    | list
    | select()
  }}

_off_extra_hosts_ips: |
  {{
    groups['all']
    | map('extract', hostvars)
    | map(attribute='extra_host_ips', default="")
    | map('split', " ")
    | list
    | flatten
    | select()
  }}


off_internal_hosts_ips_v4: |
  {{
    _off_ansible_ssh_hosts_ips
    | union(_off_extra_hosts_ips)
    | select("contains", ".")
  }}

off_internal_hosts_ips_v6: |
  {{
    _off_ansible_ssh_hosts_ips
    | union(_off_extra_hosts_ips)
    | select("contains", ":")
  }}

off_private_networks_v4:
  # local network
  - "10.0.0.0/8"
  # network used by docker
  - "172.16.0.0/12"
  - "192.168.0.0/16"

# FIXME
off_private_networks_v6:
  # local network (very wide definition: everything starting with `fd:`)
  - "fd00::/8"
