---
# users that access the system via ssh
# with their public keys taken from github
# we have a state attribute than can be 'absent' to remove the user

# base to be combined with host defined users
system_users_github__authorized_users_base:
  - name: alex
    github_name: alexgarel
    is_superuser: true
    state: present
  - name: CharlesNepote
    is_superuser: true
    state: present
  - name: raphael0202
    is_superuser: true
    state: present
  - name: stephane
    is_superuser: true
    github_name: stephanegigandet
    state: present
  - name: teleboas
    is_superuser: true
    state: present
  - name: cquest
    is_superuser: true
    state: present
  - name: thomassauvage
    is_superuser: true
    state: present
# host specefic users
system_users_github__authorized_users_host: []
system_users_github__authorized_users: |
  {{
    system_users_github__authorized_users_base |
    union(system_users_github__authorized_users_host)
  }}