# variables for the Scaleway Proxmox cluster
---
# see defaults in https://github.com/lae/ansible-role-proxmox/blob/develop/defaults/main.yml
# and common vars in proxmox_nodes
# cluster name
proxmox_node__pve_cluster_enabled: true
# group name (in inventory), containing nodes.
# As a pve cluster name it must not contain "_"
# As a Ansible inventory group it must not contain "-"
proxmox_node__pve_cluster_name: "pvescaleway"
# addr1 is public ip, addr0 is defined per host
proxmox_node__pve_cluster_addr1: "{{ ansible_hostname }}"

# some common proxmox_node__zfs_filesystems to all nodes
pvescaleway_common_proxmox_node__zfs_filesystems:
  # Some ZFS file systems were created manually. We keep them out of Ansible as they might be modified manually.
  # - name: rpool
  # - name: rpool/ROOT
  # - name: rpool/ROOT/pve-1
  # - name: zfs-hdd/pve
  # - name: zfs-hdd/backups
  - name: zfs-nvme/pve

# storages,
# we need to declare all of them event if not present on all nodes
proxmox_node__pve_storages:
  - name: zfs-hdd-pve
    type: zfspool
    pool: zfs-hdd/pve
    content: rootdir,images
    mountpoint: /zfs-hdd/pve
    sparse: 0
  - name: zfs-nvme-pve
    type: zfspool
    pool: zfs-nvme/pve
    content: rootdir,images
    mountpoint: /zfs-nvme/pve
    sparse: 0
  - name: local
    type: dir
    path: /var/lib/vz
    content: vztmpl,snippets,iso
    shared: 0
  # removing installed storage
  - name: zfs-hdd
    type: zfspool
    pool: zfs-hdd
    state: absent

# directory mappings
virtiofs__dir_mappings:
  - id: qm-200-virtiofs-docker-volumes
    map:
      - node: scaleway-02
        path: /zfs-hdd/virtiofs/qm-200/docker-volumes
    description: "virtiofs dataset for qm-200 docker volumes"

# FIXME
# pve_ssl_private_key
# pve_ssl_certificate

# iso files
proxmox_node__iso:
  - url: "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-13.1.0-amd64-netinst.iso"
    checksum: "sha256:https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/SHA256SUMS"

# Access to PVE
proxmox_api_user: thomassauvage@pve
proxmox_api_token_id: ansible-token
