# /etc/fail2ban/jail.d/wordpress.conf

[wordpress]
enabled = true
port = http,https
filter = wordpress
# nginx logs to analyse
logpath = /var/log/nginx/blog.access.log
# How many 'strikes' or 'chances' the ip gets before ban
maxretry = 5
# Time IP banned for. Can also use seconds. Shorthand info in jail.conf(5)
bantime = 12 hours
# Maxretry must be found during this findtime; default to 600 seconds, which I find too low
findtime = 12 hours
ignoreip = 10.1.0.0/16 ; internal
    146.59.148.140 ; ovh1
    51.210.154.203 ; ovh2
    51.210.32.79 ; ovh3
    46.105.72.120 ; proxy ovh1
    213.36.253.215 ; proxy off1
    213.36.253.214 ; proxy off2
    213.36.253.206 ; off1
    213.36.253.208 ; off2
    45.147.209.254 ; moji
    217.182.132.133 ; ks1

