# Add labels to any any pull request with changes to the specified paths

# Pull requests that update GitHub Actions code. If you navigate to the folder, you will have a README of what it does
GitHub Actions:
- changed-files:
  - any-glob-to-any-file: '.github/**/*'

postmortems:
- changed-files:
  - any-glob-to-any-file: 'docs/reports/**/*'

openfoodfacts-query:
- changed-files:
  - any-glob-to-any-file: 'docs/openfoodfacts-query.md'
