---
- name: "Hetzner_vswitch : restart vswitch"
  ansible.builtin.shell:
    # note that vswitch might not yet exists so it's ok for ifdown to fail
    cmd: |
      ifdown {{ hetzner_vswitch__bridge_name }} || true ;
      ifdown {{ hetzner_vswitch__interface }}.{{ hetzner_vswitch__vlan_id }} || true ;
      ifup {{ hetzner_vswitch__interface }}.{{ hetzner_vswitch__vlan_id }}
      ifup {{ hetzner_vswitch__bridge_name }} ;
  changed_when: true
