# Create a container
# _container contains the information
---
- name: Ensure CT id is > 100 < 200
  ansible.builtin.fail:
    msg: |
      CT must have an id between 100 and 200 (current: {{ _container.id }})
  when: |
    (( _container.id | int ) < 100) or (( _container.id | int ) > 200)

- name: Get name of local debian template
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      set -o pipefail
      pveam list local |
      grep -o '[^ ]*debian-{{ ansible_distribution_major_version }}.*standard[^ ]*'
  changed_when: false
  register: _proxmox_containers__debian_template_local_name

# we need this to determine if we need a restart
- name: Get current container information
  community.proxmox.proxmox_vm_info:
    api_host: "{{ proxmox_containers__api_host }}"
    api_port: "{{ proxmox_containers__api_port }}"
    validate_certs: false
    api_user: "{{ proxmox_containers__api_user }}"
    api_token_id: "{{ proxmox_containers__api_token_id }}"
    api_token_secret: "{{ proxmox_containers__api_token_secret }}"
    vmid: "{{ _container.id | mandatory }}"
    config: current
    network: true
  delegate_to: localhost
  become: false
  register: _proxmox_containers__container_before

# whereas we need this to determine if rootfs is already there
- name: Verify if container already exists
  community.proxmox.proxmox_vm_info:
    api_host: "{{ proxmox_containers__api_host }}"
    api_port: "{{ proxmox_containers__api_port }}"
    validate_certs: false
    api_user: "{{ proxmox_containers__api_user }}"
    api_token_id: "{{ proxmox_containers__api_token_id }}"
    api_token_secret: "{{ proxmox_containers__api_token_secret }}"
    vmid: "{{ _container.id | mandatory }}"
    # we need to grab rootfs information
    config: pending
    # needed to get existing hwaddr
    network: true
  delegate_to: localhost
  become: false
  register: _proxmox_containers__existing_container

- name: Compute rootfs options
  ansible.builtin.set_fact:
    _proxmox_containers__disk_settings: |
      {{
        _container.disk |
        proxmox_process_disk_volume(
          existing=_proxmox_containers__existing_container.proxmox_vms.0 | default(None),
          defaults={
            'storage': proxmox_containers__default_disk_storage,
            'options': proxmox_containers__default_disk_options,
            'size': proxmox_containers__default_disk_size,
          }
        )
      }}

- name: Create container
  community.proxmox.proxmox:
    api_host: "{{ proxmox_containers__api_host }}"
    api_port: "{{ proxmox_containers__api_port }}"
    validate_certs: false
    api_user: "{{ proxmox_containers__api_user }}"
    api_token_id: "{{ proxmox_containers__api_token_id }}"
    api_token_secret: "{{ proxmox_containers__api_token_secret }}"
    # first screen of creation form
    node: "{{ inventory_hostname }}"
    vmid: "{{ _container.id | mandatory }}"
    hostname: "{{ _container.hostname | mandatory }}"
    features: "{{ _container.features | default(proxmox_containers__default_features) }}"
    unprivileged: "{{ _container.unprivileged | default(proxmox_containers__default_unprivileged) }}"
    tags: "{{ _container.tags | default([]) }}"
    # throwaway password for root
    password: "{{ lookup('community.general.random_string', length=16) }}"
    # 2nd screen of creation form
    ostemplate: "{{ _proxmox_containers__debian_template_local_name.stdout_lines | first | mandatory }}"
    # 3rd screen of creation form
    disk_volume: "{{ _proxmox_containers__disk_settings }}"
    # 4th screen of creation form
    cores: "{{ _container.cores | default(proxmox_containers__default_cores) }}"
    # 5th screen of creation form
    memory: "{{ _container.memory | default(proxmox_containers__default_memory) }}"
    swap: "{{ _container.swap | default(proxmox_containers__default_swap) }}"
    # 6th screen of creation form
    netif: "{{ _container.netif | proxmox_netif_dict(current_config=(_proxmox_containers__existing_container.proxmox_vms[0].network | default(None))) }}"
    # more options
    onboot: "{{ _container.onboot | default(proxmox_containers__default_onboot) }}"
    # NOTE: protection is not supported :-(
    # state, we must use present to have container updated
    state: "{{ _container.state | default('started') | replace('started', 'present') | replace('stopped', 'present') }}"
  # proxmoxer dependency makes it easier to run on localhost
  delegate_to: localhost
  become: false
  register: _proxmox_containers__container_update

# if there are idmaps add them
- name: Add idmap to container configuration
  ansible.builtin.include_tasks:
    file: container_idmap.yml
  when: _container.idmap | default([])

- name: Check current VM status
  community.proxmox.proxmox_vm_info:
    api_host: "{{ proxmox_containers__api_host }}"
    api_port: "{{ proxmox_containers__api_port }}"
    validate_certs: false
    api_user: "{{ proxmox_containers__api_user }}"
    api_token_id: "{{ proxmox_containers__api_token_id }}"
    api_token_secret: "{{ proxmox_containers__api_token_secret }}"
    # first screen of creation form
    node: "{{ inventory_hostname }}"
    vmid: "{{ _container.id | mandatory }}"
    config: current
    network: true
  # proxmoxer dependency makes it easier to run on localhost
  delegate_to: localhost
  become: false
  register: _proxmox_containers__container_info

# _proxmox_containers__existing_container.change is always true, whereas it should not…
# so we use the two states we got from proxmox_vm_info to check for ourselves
- name: Compute if there was a configuration change
  ansible.builtin.set_fact:
    _proxmox_containers__config_changed: |
      {{
        (not _proxmox_containers__existing_container.proxmox_vms | default(None))
        or
        (
          _proxmox_containers__container_before.proxmox_vms[0].config
          !=
          _proxmox_containers__container_info.proxmox_vms[0].config
        )
        or (_proxmox_containers__sub_id_content.changed | default(False))
        or (_proxmox_containers__etc_subuid_edit.changed | default(False))
      }}

- name: Restart container if it has changed, or start if just created
  community.proxmox.proxmox:
    api_host: "{{ proxmox_containers__api_host }}"
    api_port: "{{ proxmox_containers__api_port }}"
    validate_certs: false
    api_user: "{{ proxmox_containers__api_user }}"
    api_token_id: "{{ proxmox_containers__api_token_id }}"
    api_token_secret: "{{ proxmox_containers__api_token_secret }}"
    # first screen of creation form
    node: "{{ inventory_hostname }}"
    vmid: "{{ _container.id | mandatory }}"
    state: >-
      {{
        'restarted'
        if (
          _proxmox_containers__existing_container.proxmox_vms and
          (_proxmox_containers__container_info.proxmox_vms.0.status | default('')) == 'running'
        )
        else 'started'
      }}
  when: |
    _proxmox_containers__config_changed and
    ( _container.state | default('started') ) == 'started'
  delegate_to: localhost
  become: false

- name: Dummy set fact to get an anchor on common pct connexion variables
  ansible.builtin.set_fact:
    _proxmox_containers_pct_connection: &pct_connection
      # pct_remote does not need to become (in the container),
      # as it use pct exec (which already exec as root)
      become: false
      connection: community.proxmox.proxmox_pct_remote
      vars:
        proxmox_vmid: "{{ _container.id | mandatory }}"
        # don't be too specific on interpreter version
        ansible_python_interpreter: "/usr/bin/python3"

- name: Install sudo using the lxc connection plugin # noqa: key-order
  ansible.builtin.apt:
    pkg:
      - sudo
    update_cache: true
  <<: *pct_connection

- name: Bootstrap config-op user using the lxc connection plugin # noqa: key-order
  ansible.builtin.user:
    name: "{{ ansible_ssh_user }}"
    shell: /bin/bash
    create_home: true
    groups: ["sudo"]
    password: >-
      {{
        hostvars[_container.hostname].ansible_become_password |
        password_hash('sha512', hostvars[_container.hostname].ansible_user_password_salt)
      }}
    state: present
  <<: *pct_connection

- name: Bootstrap config-op ssh connection using the lxc connection plugin # noqa: key-order
  ansible.posix.authorized_key:
    user: "{{ ansible_ssh_user }}"
    key: "{{ proxmox_containers__github_url }}/{{ item.github_name | default(item.name) }}.keys"
    state: present
  loop: "{{ proxmox_containers__github_authorized_users }}"
  <<: *pct_connection

# Tricky, because we use pct enter commands,
# it might create file owned by root in config-op user
# fix permissions
- name: Fix permissions on config-op home # noqa: key-order
  ansible.builtin.file:
    path: "/home/{{ ansible_ssh_user }}"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    recurse: true
  <<: *pct_connection
