# Create a container
# _container contains the information
---
- name: Ensure CT id is > 100 < 200
  ansible.builtin.fail:
    msg: |
      CT must have an id between 100 and 200 (current: {{ _container.id }})
  when: |
    (( _container.id | int ) < 100) or (( _container.id | int ) > 200)

- name: Get name of local debian template
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      set -o pipefail
      pveam list local |
      grep -o '[^ ]*debian-{{ ansible_distribution_major_version }}.*standard[^ ]*'
  changed_when: false
  register: _debian_template_local_name

- name: Verify if container already exists
  community.proxmox.proxmox_vm_info:
    api_host: "{{ proxmox_containers__api_host }}"
    api_port: "{{ proxmox_containers__api_port }}"
    validate_certs: false
    api_user: "{{ proxmox_containers__api_user }}"
    api_token_id: "{{ proxmox_containers__api_token_id }}"
    api_token_secret: "{{ proxmox_containers__api_token_secret }}"
    vmid: "{{ _container.id | mandatory }}"
  delegate_to: localhost
  become: false
  register: existing_container

- name: Compute default rootfs volume name
  ansible.builtin.set_fact:
    _rootfs_default_volume_name: "subvol-{{ _container.id }}-disk-0"

# needed for next action
- name: Get storage information
  community.proxmox.proxmox_storage_info:
    api_host: "{{ proxmox_containers__api_host }}"
    api_port: "{{ proxmox_containers__api_port }}"
    validate_certs: false
    api_user: "{{ proxmox_containers__api_user }}"
    api_token_id: "{{ proxmox_containers__api_token_id }}"
    api_token_secret: "{{ proxmox_containers__api_token_secret }}"
    storage: "{{ _container.disk.storage | default(proxmox_containers__default_disk_storage) }}"
  # proxmoxer dependency makes it easier to run on localhost
  delegate_to: localhost
  become: false
  register: _storage_info
  when: "(_container.state | default('started')) in ('present', 'started')"

# normally community.proxmox.proxmox would use a special syntax
# just specifying the storage and volume size, but it does not work…
# so we create the volume manually with zfs
- name: Create the rootfs volume
  community.general.zfs:
    name: "{{ _storage_info.proxmox_storages[0].pool }}/{{ _container.disk.volume | default(_rootfs_default_volume_name) }}"
    state: present
    extra_zfs_properties:
      refquota: "{{ _container.disk.size | default(proxmox_containers__default_disk_size) | trim('Gg') }}G"
      # needed by proxmox
      acltype: posix
      xattr: sa
  when: "(_container.state | default('started')) in ('present', 'started')"

- name: Give rootfs volume to right user
  ansible.posix.acl:
    path: "/{{ _storage_info.proxmox_storages[0].pool }}/{{ _container.disk.volume | default(_rootfs_default_volume_name) }}"
    entity: 100000
    etype: "{{ item }}"
    permissions: "rwX"
    state: "present"
  loop: ["user", "group"]

- name: Create container
  community.proxmox.proxmox:
    api_host: "{{ proxmox_containers__api_host }}"
    api_port: "{{ proxmox_containers__api_port }}"
    validate_certs: false
    api_user: "{{ proxmox_containers__api_user }}"
    api_token_id: "{{ proxmox_containers__api_token_id }}"
    api_token_secret: "{{ proxmox_containers__api_token_secret }}"
    # first screen of creation form
    node: "{{ inventory_hostname }}"
    vmid: "{{ _container.id | mandatory }}"
    hostname: "{{ _container.hostname | mandatory }}"
    features: "{{ _container.features | default(proxmox_containers__default_features) }}"
    unprivileged: "{{ _container.unprivileged | default(proxmox_containers__default_unprivileged) }}"
    tags: "{{ _container.tags | default([]) }}"
    # throwaway password for root
    password: "{{ lookup('community.general.random_string', length=16) }}"
    # 2nd screen of creation form
    ostemplate: "{{ _debian_template_local_name.stdout_lines | first | mandatory }}"
    # 3rd screen of creation form
    disk_volume:
      storage: "{{ _container.disk.storage | default(proxmox_containers__default_disk_storage) }}"
      volume: "{{ _container.disk.volume | default(_rootfs_default_volume_name) }}"
      options: "{{ _container.disk.options | default(proxmox_containers__default_disk_options) }}"
      size: "{{ _container.disk.size | default(proxmox_containers__default_disk_size) }}"
    # 4th screen of creation form
    cores: "{{ _container.cores | default(proxmox_containers__default_cores) }}"
    # 5th screen of creation form
    memory: "{{ _container.memory | default(proxmox_containers__default_memory) }}"
    swap: "{{ _container.swap | default(proxmox_containers__default_swap) }}"
    # 6th screen of creation form
    netif: "{{ _container.netif | proxmox_netif_dict }}"
    # more options
    onboot: "{{ _container.onboot | default(proxmox_containers__default_onboot) }}"
    # NOTE: protection is not supported :-(
    # state, we must use present to have container updated
    state: "{{ _container.state | default('started') | replace('started', 'present') | replace('stopped', 'present') }}"
  # proxmoxer dependency makes it easier to run on localhost
  delegate_to: localhost
  become: false
  register: _container_update

- name: Restart container if it has changed, or start if just created
  community.proxmox.proxmox:
    api_host: "{{ proxmox_containers__api_host }}"
    api_port: "{{ proxmox_containers__api_port }}"
    validate_certs: false
    api_user: "{{ proxmox_containers__api_user }}"
    api_token_id: "{{ proxmox_containers__api_token_id }}"
    api_token_secret: "{{ proxmox_containers__api_token_secret }}"
    # first screen of creation form
    node: "{{ inventory_hostname }}"
    vmid: "{{ _container.id | mandatory }}"
    state: "{{ 'restarted' if existing_container.proxmox_vms else 'started' }}"
  when: |
    _container_update.changed and
    ( _container.state | default('started') ) == 'started'
  delegate_to: localhost
  become: false

- name: Bootstrap config-op user using the lxc connection plugin
  ansible.builtin.user:
    name: config-op
    shell: /bin/bash
    create_home: true
    state: present
  # pct_remote does not need to become (in the container),
  # as it use pct exec (which already exec as root)
  become: false
  connection: community.proxmox.proxmox_pct_remote
  vars:
    proxmox_vmid: "{{ _container.id | mandatory }}"
