# https redirect
server {
    if ($host = ovh-exporters.openfoodfacts.org) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    listen [::]:80;
    server_name ovh-exporters.openfoodfacts.org;

    location /.well-known {
        root /var/www/html;
        try_files $uri =404;
    }
    return 404;
}


# map from service to exporter
# We follow the schema job/env/app/service
map $uri $exporter {
    # docker-cadvisor
    "/docker-cadvisor/net/docker/cadvisor/metrics" 10.1.0.200:8280;
    "/docker-prod/org/docker/cadvisor/metrics" 10.1.0.201:8280;
    # node exporter
    "/node-exporter/net/system/vm/metrics" 10.1.0.200:8281;
    "/node-exporter/org/system/vm/metrics" 10.1.0.201:8281;
    # docker nginx
    "/docker-nginx/net/off/frontend/metrics" 10.1.0.200:9113;
    # docker apache
    "/docker-apache/net/off/backend/metrics" 10.1.0.200:9113;
    # docker-statsd (for robotoff gunicorn)
    "/docker-statsd/net/robotoff/api/metrics" 10.1.0.200:9102;
    # moved to moji "/docker-statsd/org/robotoff/api/metrics" 10.1.0.201:9102;
    # docker-postgres
    "/docker-postgres/net/robotoff/postgres/metrics" 10.1.0.200:9187;
    # moved to moji - "docker-postgres/org/robotoff/postgres/metrics" 10.1.0.201:9187;
    # Proxmox gateway postfix
    "/pmg-postfix/prod/pmg/postfix/metrics" 10.1.0.102:9154;
    # docker-elasticsearch
    "/docker-elasticsearch/net/search-a-licious/elasticsearch/metrics" 10.1.0.200:9114;
    "/docker-elasticsearch/org/search-a-licious/elasticsearch/metrics" 10.1.0.201:9114;
    # matomo mysqld
    "/mysqld/prod/matomo/mysqld" 10.1.0.107:9104;
    # matomo nginx
    "/mysqld/prod/matomo/nginx" 10.1.0.107:9113;
}

#log_format debug_exporter "$time_local $scheme://$host:$server_port$request_uri $exporter";

# https server
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ovh-exporters.openfoodfacts.org;

    # SSL/TLS settings
    ssl_certificate /etc/letsencrypt/live/ovh-exporters.openfoodfacts.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ovh-exporters.openfoodfacts.org/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/ovh-exporters.openfoodfacts.org/chain.pem;

    # logs location, avoid access_log, no need
    #access_log  /var/log/nginx/ovh-exporters.log  debug_exporter;
    #access_log  /var/log/nginx/ovh-exporters.log  main;
    access_log  off;
    error_log   /var/log/nginx/ovh-exporters.errors.log;

    # protect
    auth_basic "Exporter metrics";
    auth_basic_user_file "/etc/nginx/.htpasswd/ovh-exporters";

    # url to join is defined thanks to exporter variable, itself based upon uri
    location / {

        if ($exporter = "") {
            return 404;
        }
        proxy_pass http://$exporter/metrics;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Host $host;
        client_max_body_size 512M;
    }
}



