server {

    server_name  sc1.epy.ovh;

    access_log  /var/log/nginx/sc1.epy.ovh.access.log  main;

    location / {
        proxy_pass          http://10.13.1.142:8000;
        proxy_set_header    Host $host;
        proxy_set_header    X-Real-IP $remote_addr;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto $scheme;
    }


    listen 443 ssl; # managed by Certbot
    listen [::]:443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/sc1.epy.ovh/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/sc1.epy.ovh/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}

server {
    if ($host = sc1.epy.ovh) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name  sc1.epy.ovh;

    listen 80;
    listen [::]:80;
    return 404; # managed by Certbot
}
