---
- name: Check if user exists
  ansible.builtin.command: id {{ user.name }}
  become: true
  ignore_errors: true
  register: _system_users__user_exists_cmd
  changed_when: false

- name: Create/update group
  ansible.builtin.group:
    name: "{{ user.name }}"
    gid_min: 1000
    state: "{{ user.state | default('present') }}"

- name: Create/update user
  ansible.builtin.user:
    name: "{{ user.name }}"
    group: "{{ user.name }}"
    groups: "{{ ['adm', 'sudo'] if user.is_superuser else '' }}"
    state: "{{ user.state | default('present') }}"
    shell: "{{ '/usr/bin/false' if not user_has_password else '/bin/bash' }}"
    # We use a '*' password and handle users with password later
    password: "*"
    update_password: "on_create"

- name: Force user to set password on first login
  when: user_has_password and _system_users__user_exists_cmd.rc != 0
  ansible.builtin.command: "passwd -e -d {{ user.name }}"
  changed_when: true

- name: Authorize ssh public key from github for this user
  ansible.posix.authorized_key:
    user: "{{ user.name }}"
    key: "{{ system_users__github_url }}/{{ user.github_name | default(user.name) }}.keys"
