# Handle system users creation / removal
---
- name: "Handle user creation"
  ansible.builtin.include_tasks: create_user.yml
  vars:
    user: "{{ item }}"
    user_has_password: "{{ (not system_users__is_jump_proxy) or item.is_superuser }}"
    user_password_dir: '{{ lookup("repo", "keys", filename=True) }}/{{ item.name }}'
  loop: "{{ system_users_github__authorized_users }}"
  loop_control:
    label: "{{ item.name }}"
  tags: "user"
