# getting ZFS datasets infos
---
- name: Get ZFS pools
  community.general.zpool_facts:
    properties: "name"
  register: _virtiofs__zfs_pools

- name: Get ZFS datasets
  community.general.zfs_facts:
    name: "{{ item }}"
    recurse: true
    type: filesystem
    properties: "name,mountpoint,acltype"
  register: _virtiofs__zfs_datasets_data
  loop: "{{ _virtiofs__zfs_pools.ansible_facts.ansible_zfs_pools | map(attribute='name') }}"

- name: Combine ZFS datasets
  ansible.builtin.set_fact:
    _virtiofs__zfs_datasets: |
      {{
        ( _virtiofs__zfs_datasets | default([]) ) + item.ansible_facts.ansible_zfs_datasets
      }}
  loop: "{{ _virtiofs__zfs_datasets_data.results }}"
