---
- name: Common configuration
  hosts: all:!non_ansible_hosts
  gather_facts: true
  become: true
  roles:
    - role: base
      tags: base
    - role: sshd
      tags: ssh
    - role: system_users
      tags: users
    - role: nullmailer
      tags: mail
    - role: iptables
      tags: ["firewall", "iptables"]
    - role: fail2ban_iptables
      tags: fail2ban
    - role: systemd_email_failures
      tags: ["systemd", "alerts"]
# TODO
#    - role: munin-node
#      tags: [munin, munin-node]
#    - firewall DENY input + verify ssh rule
#    - set locale en_US + fr_FR
