---
- name: Pull proxmox cluster config files
  hosts: hetzner-01:scaleway-01
  gather_facts: false
  become: true
  roles:
    - name: pull_pve_configs
      tags: ["pve", "proxmox"]
    - name: pull_zfs_config
      tags: ["zfs"]
