# Deployment of folksonomy engine
---
- name: Verify we have a version
  ansible.builtin.assert:
    that:
      - "{{ folksonomy_api__version }}"
    fail_msg: |
      Please provide a version for folksonomy API using --extra-vars and folksonomy_api__version
      You can use "latest" to fetch latest version

- name: Get latest release of folksonomy
  community.general.github_release:
    user: "{{ folksonomy_api__repository_owner }}"
    repo: "{{ folksonomy_api__repository_name }}"
    action: latest_release
  register: _latest_release
  when: "folksonomy_api__version == 'latest'"

- name: Get version to install
  ansible.builtin.set_fact:
    _git_ref: >-
      {{
        _latest_release if folksonomy_api__version == 'latest' else folksonomy_api__version
      }}

- name: Checkout the right ref
  ansible.builtin.git:  # noqa: latest
    repo: "git@github.com:{{ folksonomy_api__repository_owner }}/{{ folksonomy_api__repository_name }}.git"
    dest: "{{ folksonomy_api__install_directory }}"
    version: "{{ _git_ref }}"
    update: true
  become: true
  become_user: "{{ folksonomy_api__username }}"

- name: Install the project dependencies
  ansible.builtin.command:
    cmd: poetry install
    chdir: "{{ folksonomy_api__install_directory }}"
  register: _poetry_install
  changed_when: |
    "No dependencies to install or update" not in _poetry_install.stdout
  become: true
  become_user: "{{ folksonomy_api__username }}"
  tags: ["install", "deploy"]

- name: Get confs dirs
  ansible.builtin.find:
    paths: "{{ folksonomy_api__install_directory }}/confs"
    recurse: true
    file_type: directory
  register: _confs_dirs
  tags: ["install", "deploy"]

- name: Verify we have our expected confs dir
  ansible.builtin.fail:
    msg: "There are unknown or missing confs dir (you may need to update this role)"
  when: |
    (
      _confs_dirs.files|map(attribute='path')|map('basename')|sort
    ) != [
      'systemd'
    ]
  tags: ["install", "deploy"]

- name: Symlink configurations files
  git_based_config_symlinks:
    src: "{{ folksonomy_api__install_directory }}/confs/systemd"
    dst: "/etc/systemd/system"
  tags: ["install", "deploy"]
  register: _systemd_config_symlinks

- name: Run yoyo migrations
  ansible.builtin.command:
    cmd: poetry run yoyo apply  --batch --database postgresql:///{{ folksonym_api__db_name }}
  register: _yoyo_migrations
  changed_when: len(_yoyo_migrations.stdout_lines) > 0
  tags: ["install", "deploy"]

- name: Enable service and (re)-start
  ansible.builtin.import_role:
    name: git_based_configs
    tasks_from: enable_service.yml
  vars:
    git_based_configs__service_name: folksonomy.service
  tags: ["install", "deploy"]
