# {{ ansible_managed }}


{% for site in reverse_proxy_docker__websites %}

{% set dashed_name = (site.url | replace(".", "_")) %}
# ============ {{ site.url }} ============

{% if (site.public_paths|default([])) %}
# exclude some url from basic auth
map $uri ${{ dashed_name }}_basic_auth {
  default "{{ site.url }}";
{% for public_path in site.public_paths %}
  {{ public_path }} "off";
{% endfor %}
}
{% endif %}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name  {{ site.url }};
    
    location / {
        proxy_pass http://{{ site.proxy_pass }}$request_uri;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 90;
        client_max_body_size 512M;
    }

{% if site.password is defined %}
  {% if (site.public_paths|default([])) %}
        auth_basic ${{ dashed_name }}_basic_auth;
  {% else %}
        auth_basic "{{ site.url }}";
  {% endif %}
        auth_basic_user_file /etc/nginx/passwords/{{ site.url }};
{% endif %}

    # managed by Certbot
    ssl_certificate /etc/nginx/ssl/live/certificate/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/live/certificate/privkey.pem;
}
{% endfor %}

# ============ default (404) ============

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_name  _;

    location / {
        return 404;
    }

    # managed by Certbot
    ssl_certificate /etc/nginx/ssl/live/certificate/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/live/certificate/privkey.pem;
}

# ============ redirect all http to https ============

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name  _;

    location / {
        return 301 https://$host$request_uri;
    }
}

