proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto https;
proxy_set_header Host $host;
client_max_body_size 512M;

proxy_intercept_errors on;
error_page 502 /502.html;
error_page 503 /503.html;

# Adds an X-Cache-Status HTTP header in responses to clients: helps debugging the
# cache.
# https://www.nginx.com/blog/nginx-caching-guide/#Frequently-Asked-Questions-(FAQ)
# Eg. X-Cache-Status: HIT
add_header X-Cache-Status $upstream_cache_status;
