# saving our cluster pve files
# scaleway-01.infra.openfoodfacts.org is currently only defined in /etc/hosts, not in DNS
--no-sync-snap --no-privilege-elevation --recursive scaleway03operator@scaleway-01.infra.openfoodfacts.org:zfs-hdd/pve zfs-hdd/backups/scaleway-01-pve
--no-sync-snap --no-privilege-elevation --recursive scaleway03operator@scaleway-02.infra.openfoodfacts.org:zfs-hdd/pve zfs-hdd/backups/scaleway-02-pve
