# saving our cluster pve files
--no-sync-snap --no-privilege-elevation --recursive scaleway03operator@scaleway-01.infra.openfoodfacts.org:zfs-hdd/pve zfs-hdd/off-backups/scaleway-01-pve
--no-sync-snap --no-privilege-elevation --recursive scaleway03operator@scaleway-01.infra.openfoodfacts.org:zfs-nvme/pve zfs-hdd/off-backups/scaleway-01-nvme-pve
--no-sync-snap --no-privilege-elevation --recursive scaleway03operator@scaleway-02.infra.openfoodfacts.org:zfs-hdd/pve zfs-hdd/off-backups/scaleway-02-pve
--no-sync-snap --no-privilege-elevation --recursive scaleway03operator@scaleway-02.infra.openfoodfacts.org:zfs-nvme/pve zfs-hdd/off-backups/scaleway-02-nvme-pve
--no-sync-snap --no-privilege-elevation --recursive scaleway03operator@scaleway-02.infra.openfoodfacts.org:zfs-hdd/virtiofs zfs-hdd/off-backups/scaleway-02-virtiofs
--no-sync-snap --no-privilege-elevation --recursive scaleway03operator@scaleway-02.infra.openfoodfacts.org:zfs-nvme/virtiofs zfs-hdd/off-backups/scaleway-02-nvme-virtiofs

# product opener data
--no-sync-snap --no-privilege-elevation --recursive scaleway03operator@scaleway-01.infra.openfoodfacts.org:zfs-hdd/podata zfs-hdd/off-backups/scaleway-01-podata-hdd
--no-sync-snap --no-privilege-elevation --recursive scaleway03operator@scaleway-01.infra.openfoodfacts.org:zfs-nvme/podata zfs-hdd/off-backups/scaleway-01-podata-nvme

# we cross backup rpool of scaleway cluster
--no-sync-snap --no-privilege-elevation --recursive scaleway03operator@scaleway-01.infra.openfoodfacts.org:rpool zfs-hdd/off-backups/scaleway-01/rpool
--no-sync-snap --no-privilege-elevation --recursive scaleway03operator@scaleway-02.infra.openfoodfacts.org:rpool zfs-hdd/off-backups/scaleway-02/rpool

