# variables for the Hetzner Proxmox cluster
---
# see defaults in https://github.com/lae/ansible-role-proxmox/blob/develop/defaults/main.yml
# and specific vars in each cluster group

# General ######

proxmox_node__alerts_email: "{{ secrets_root_email }}"

# permissions ######

# for privacy reasons, it's in proxmox-secrets.yml
proxmox_node__pve_users: "{{ secrets_pve_users }}"

proxmox_node__pve_groups:
  - name: ro_users
    comment: Read only ro_users
  - name: admins
    comment: Administrators
proxmox_node__pve_acls:
  - path: /
    roles: ["Administrator"]
    groups: ["admins"]
  - path: /
    roles: ["PVEAuditor"]
    groups: ["ro_users"]
proxmox_node__pve_storages:
  - name: localdir
    type: dir
    content: ["images", "iso", "backup"]
    path: /plop
    maxfiles: 4

# ZFS ###########

# this is a variable that can be used for proxmox_node__zfs_pools.filesystem_properties
proxmox_node__zfs_pools_filesystem_properties_defaults:
  compression: "on"
  xattr: "sa"
  atime: "off"
  relatime: "on"
