---
- name: Create user who will run the triton server through Docker
  ansible.builtin.user:
    name: "{{ triton_gpu__user }}"
    comment: "User who launches docker containers"
    append: true
    groups: docker # append the docker group to the user, to allow docker commands
    create_home: true
    state: present
    shell: /bin/bash
    password: "*"

- name: Install git
  ansible.builtin.package:
    name: git
    state: present

- name: Install uv by launching the install script
  ansible.builtin.shell:
    cmd: set -o pipefail && curl -LsSf https://astral.sh/uv/install.sh | sh
    executable: /bin/bash
    # Don't launch if '/home/off/.local/bin/uv' exists
    creates: "/home/{{ triton_gpu__user }}/.local/bin/uv"
  become: true
  become_user: "{{ triton_gpu__user }}"

- name: Clone of the Robotoff repository
  ansible.builtin.git: # noqa: latest
    repo: "https://github.com/{{ triton_gpu__repository_owner }}/{{ triton_gpu__repository_name }}.git"
    dest: "{{ triton_gpu__repository_dest }}"
    update: false
    accept_newhostkey: true
  become: true
  become_user: "{{ triton_gpu__user }}"

- name: Copying the .env file
  ansible.builtin.copy:
    src: "files/env_file"
    dest: "{{ triton_gpu__repository_dest }}/models/.env"
    owner: "{{ triton_gpu__user }}"
    group: "{{ triton_gpu__user }}"
    mode: "0600"

- name: Configure the production repository for NVIDIA Container Too # noqa: risky-shell-pipe command-instead-of-module
  ansible.builtin.shell:
    cmd: |
      curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg && \
      curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
        sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
        sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
  args:
    creates: /etc/apt/sources.list.d/nvidia-container-toolkit.list

- name: Update the packages list from the repository
  ansible.builtin.apt:
    update_cache: true

- name: Install the NVIDIA Container Toolkit packages
  ansible.builtin.apt:
    name:
      - nvidia-container-toolkit=1.18.1-1
      - nvidia-container-toolkit-base=1.18.1-1
      - libnvidia-container-tools=1.18.1-1
      - libnvidia-container1=1.18.1-1
    state: present

- name: Configure the docker container runtime with `nvidia-ctk`
  ansible.builtin.shell: |
    nvidia-ctk runtime configure --runtime=docker
  changed_when: true

- name: Restart docker to apply nvidia runtime configuration
  ansible.builtin.systemd_service:
    name: docker
    state: restarted
    enabled: true

- name: "Download all models for Triton server"
  ansible.builtin.shell:
    cmd: /home/{{ triton_gpu__user }}/.local/bin/uv run manage.py download-models
    chdir: "{{ triton_gpu__repository_dest }}/models"
    executable: /bin/bash
  changed_when: true
  become: true
  become_user: "{{ triton_gpu__user }}"

- name: "Copy Triton config"
  ansible.builtin.shell:
    cmd: /home/{{ triton_gpu__user }}/.local/bin/uv run manage.py copy-config
    chdir: "{{ triton_gpu__repository_dest }}/models"
    executable: /bin/bash
  changed_when: true
  become: true
  become_user: "{{ triton_gpu__user }}"

- name: "Launching Triton server docker container"
  community.docker.docker_compose_v2:
    project_src: "{{ triton_gpu__repository_dest }}/models"
    state: present
