[Init]
# those are the bad_codes we want to monitor
# you can override it as you call the filter in your jail definition
# eg. filter = nginx-bad-codes[bad_codes=429]
# we also include 404 because we have bots crawling blindly
bad_codes=40[134]|429

[Definition]

# getting lines with codes corresponding to bad_codes
# 31.0.95.153 - - [31/Jan/2025:12:13:09 +0000] "GET /api/v3/product/5900116091877.json HTTP/2.0" 404 333 "-" "ciboulette%20scan/38 CFNetwork/1568.200.51 Darwin/24.1.0" "-" MISS [0.004]
failregex = ^<ADDR>.* "[^"]*" (<bad_codes>) \d+ ".*

# specify datepattern for it's very regular
# 31/Jan/2025:16:17:46 +0000
datepattern = \[%%d/%%b/%%Y:%%H:%%M:%%S %%z\]

ignoreregex =

