---
# A playbook to install a VM that is used to host docker containers based deployments
- name: Docker VM
  hosts: docker_vm_hosts
  gather_facts: true
  become: true
  roles:
    - role: docker
      tags: ["base", "docker"]
    - role: continuous_deployment
      tags: cd
      vars:
        # proxy jump host on vms, we get the value of proxmox_node variable
        continuous_deployment__proxy_jump_host: "{{ hostvars[ansible_hostname].proxmox_node | default(None) }}"
