# Installation of folksonomy engine in a container
---
- name: Folksonomy engine API
  hosts: folksonomy-staging
  gather_facts: true
  become: true
  roles:
    - role: postgresql
    - role: folksonomy_api
      vars:
        folksonomy_api__github_token: "{{ secret__github__bot_token_infrastructure }}"
