- name: Configure monitoring server
  hosts: monitoring-01
  gather_facts: true
  become: true
  roles:
    - role: docker
      tags: docker
    - role: continuous-deployment
      tags: cd
    - role: reverse-proxy
      tags: reverse-proxy
    # we do it last because it will require a first deployment
    - role: prometheus-secrets
      tags: prometheus-secrets
