- name: Configure monitoring server
  hosts: monitoring-01
  gather_facts: true
  become: true
  roles:
    # Install docker
    - role: geerlingguy.docker
      tags: docker
    - role: continuous-deployment
      tags: cd
