# installation of a proxmox node (host that is part of a proxmox cluster)
---
- name: Proxmox Node
  hosts: proxmox_nodes:!non_ansible_hosts
  gather_facts: true
  become: true
  roles:
    - role: proxmox_node
      tags: ["base", "proxmox", "proxmox-node"]
    - role: virtiofs
      tags: ["base", "virtiofs"]
    - role: git_based_configs
      tags: ["base", "git-config"]
      vars:
        git_based_configs__github_token: "{{ secret__github__bot_token_infrastructure }}"
        git_based_configs__repository_dest: "{{ infrastructure_repository_dest }}"
        git_based_configs__read_only_repository: false
    - role: sanoid
      tags: ["base", "sanoid"]
      vars:
        sanoid__configurations_git_root_path: "{{ infrastructure_repository_dest }}"
        sanoid__configurations_src_path: "confs/{{ ansible_hostname }}"
    - role: proxmox_containers
      tags: ["proxmox", "containers"]
      vars:
        proxmox_containers__api_port: "{{ proxmox_api_local_port }}"
        proxmox_containers__api_token_id: "{{ proxmox_api_token_id }}"
        proxmox_containers__api_token_secret: "{{ proxmox_api_token_secret }}"
        proxmox_containers__api_user: "{{ proxmox_api_user }}"
        proxmox_containers__github_authorized_users: "{{ sshd_github_authorized_users }}"
