# installation of a proxmox node (host that is part of a proxmox cluster)
---
- name: Proxmox Node
  hosts: proxmox_nodes:!non_ansible_hosts
  gather_facts: true
  become: true
  roles:
    - role: proxmox-node
      tags: ["base", "proxmox"]
    - role: git_based_configs
      tags: ["base", "git-config"]
      vars:
        git_based_configs__github_token: "{{ secret__github__bot_token_infrastructure }}"
        git_based_configs__repository_dest: "{{ infrastructure_repository_dest }}"
    - role: sanoid
      tags: ["base", "sanoid"]
      vars:
        sanoid__configurations_git_root_path: "{{ infrastructure_repository_dest }}"
        sanoid__configurations_src_path: "confs/{{ ansible_hostname }}"
    - role: hetzner_vswitch
      tags: ["base", "network", "vswitch"]
      when: hetzner_vswitch__vlan_id is defined
