# Installation of a reverse proxy container on a proxmox host
# This is the entry point for services hosted on the proxmox cluster.
#
# It has a nginx reverse-proxy. It may also have a stunnel server
---
- name: Reverse proxy container
  hosts: reverse_proxy_hosts
  gather_facts: true
  become: true
  roles:
    - role: git_based_configs
      tags: ["base", "git-config"]
      vars:
        git_based_configs__github_token: "{{ secret__github__bot_token_infrastructure }}"
        git_based_configs__repository_dest: "{{ infrastructure_repository_dest }}"
        git_based_configs__read_only_repository: false
    - role: reverse_proxy_nginx
      tags: ["nginx"]
      vars:
        reverse_proxy_nginx__nginx_git_root_path: "{{ infrastructure_repository_dest }}"
    - role: stunnel
      tags: ["stunnel"]
      # no psk means no services
      when: stunnel__psk_secrets | default(false)
      vars:
        stunnel__ensure_no_client: true
        stunnel__config_repository_root: "{{ infrastructure_repository_dest }}"
