---
# Official docs for proxmox node install
# https://pve.proxmox.com/wiki/Install_Proxmox_VE_on_Debian_Buster

- name: Prepare partitions
  ansible.builtin.import_tasks: parted.yml

# This is necessary to avoid issues with Proxmox LXC/VM consoles
- name: Ensure hosts file has localhost entry
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4"
    state: present
  tags: host_file

- name: Prepare zpool and datasets
  ansible.builtin.import_role:
    name: aisbergg.zfs
  vars:
    zfs_manage_repository: true
    zfs_service_zed_enabled: true
    zfs_scrub_schedule: monthly
    zfs_trim_schedule: weekly
    zfs_pools: "{{ proxmox_node__zfs_pools }}"
    zfs_filesystems: "{{ proxmox_node__zfs_filesystems }}"
    zfs_volumes: "{{ proxmox_node__zfs_volumes }}"
    # we prefer to use inheritance as much as possible as defaults
    zfs_filesystems_properties_defaults: {}
    zfs_zrepl_enabled: false # we use sanoid / syncoid instead
  tags: zfs

- name: Ensure zfs-mount-generator inter-zpool mount ordering cache
  ansible.builtin.import_tasks: zfs_list_cache.yml
  tags: zfs

- name: Ensure proxmox cluster name is defined, if enabled
  ansible.builtin.assert:
    that: proxmox_node__pve_cluster_enabled == false or proxmox_node__pve_cluster_name is defined
    msg: "proxmox_node__pve_cluster_name must be defined if proxmox_node__pve_cluster_enabled is true"

- name: Ensure pve_cluster_addr0 is defined if we have a cluster (don't rely on default)
  ansible.builtin.assert:
    that: proxmox_node__pve_cluster_enabled == false or proxmox_node__pve_cluster_addr0 is defined
    msg: "proxmox_node__pve_cluster_addr0 must be defined if proxmox_node__pve_cluster_enabled is true"

- name: Run proxmox node install
  ansible.builtin.import_role:
    name: lae.proxmox
  vars:
    # we are handling zfs stuff with aisbergg.zfs, above
    # but if we don't put this, the role will disable zfs loading !
    pve_zfs_enabled: true
    pve_zfs_zed_email: "{{ proxmox_node__alerts_email }}"
    pve_cluster_enabled: "{{ proxmox_node__pve_cluster_enabled }}"
    pve_group: "{{ proxmox_node__pve_cluster_name }}"
    pve_cluster_addr0: "{{ proxmox_node__pve_cluster_addr0 }}"
    pve_cluster_addr1: "{{ proxmox_node__pve_cluster_addr1 | default(null) }}"
    pve_storages: "{{ proxmox_node__pve_storages }}"
    pve_acls: "{{ proxmox_node__pve_acls }}"
    pve_groups: "{{ proxmox_node__pve_groups }}"
    pve_users: "{{ proxmox_node__pve_users }}"

  tags: proxmox

- name: Add distributions iso
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    checksum: "{{ item.checksum }}"
    dest: /var/lib/vz/template/iso
    mode: "0644"
  loop: "{{ proxmox_node__iso }}"
