---
reverse_proxy_docker__dir: "/opt/reverse_proxy"
reverse_proxy_docker__user: "reverse-proxy"

reverse_proxy_docker__websites: []
reverse_proxy_docker__https_cert_domains:
  - "openfoodfacts.org"

reverse_proxy_docker__certbot_ovh_endpoint: "ovh-eu"
reverse_proxy_docker__certbot_ovh_application_key: ""
reverse_proxy_docker__certbot_ovh_application_secret: ""
reverse_proxy_docker__certbot_ovh_consumer_key: ""
