
#--no-sync-snap --no-privilege-elevation --recursive scaleway01operator@off2.openfoodfacts.org:zfs-hdd/obf zfs-hdd/off-backups/off2-zfs-hdd/obf
--no-sync-snap --no-privilege-elevation --recursive scaleway01operator@off2.openfoodfacts.org:zfs-hdd/off zfs-hdd/off-backups/off2-zfs-hdd/off
#--no-sync-snap --no-privilege-elevation --recursive scaleway01operator@off2.openfoodfacts.org:zfs-hdd/off-pro zfs-hdd/off-backups/off2-zfs-hdd/off-pro
# --no-sync-snap --no-privilege-elevation --recursive scaleway01operator@off2.openfoodfacts.org:zfs-hdd/off-pro-products-old zfs-hdd/backups/off2-zfs-hdd/off-pro-products-old
# --no-sync-snap --no-privilege-elevation --recursive scaleway01operator@off2.openfoodfacts.org:zfs-hdd/ofsf zfs-hdd/backups/off2-zfs-hdd/ofsf
#--no-sync-snap --no-privilege-elevation --recursive scaleway01operator@off2.openfoodfacts.org:zfs-hdd/opf zfs-hdd/off-backups/off2-zfs-hdd/opf
#--no-sync-snap --no-privilege-elevation --recursive scaleway01operator@off2.openfoodfacts.org:zfs-hdd/opff zfs-hdd/off-backups/off2-zfs-hdd/opff
--no-sync-snap --no-privilege-elevation --recursive scaleway01operator@off2.openfoodfacts.org:zfs-hdd/pve zfs-hdd/off-backups/off2-zfs-hdd/pve

--no-sync-snap --no-privilege-elevation --recursive scaleway01operator@off2.openfoodfacts.org:zfs-nvme/off zfs-nvme/off-backups/off2-zfs-nvme/off
#--no-sync-snap --no-privilege-elevation --recursive scaleway01operator@off2.openfoodfacts.org:zfs-nvme/off-pro zfs-nvme/off-backups/off2-zfs-nvme/off-pro
# --no-sync-snap --no-privilege-elevation --recursive scaleway01operator@off2.openfoodfacts.org:zfs-nvme/ofsf zfs-hdd/backups/off2-zfs-nvme/ofsf
--no-sync-snap --no-privilege-elevation --recursive scaleway01operator@off2.openfoodfacts.org:zfs-nvme/pve zfs-nvme/off-backups/off2-zfs-nvme/pve

# Note: zfs-hdd/logs-nginx, zfs-hdd/backups and zfs-hdd/off-backups are intentionally omitted.

# we cross backup rpool of scaleway cluster
--no-sync-snap --no-privilege-elevation --recursive scaleway01operator@scaleway-02.infra.openfoodfacts.org:rpool zfs-hdd/off-backups/scaleway-02/rpool
--no-sync-snap --no-privilege-elevation --recursive scaleway01operator@scaleway-03.infra.openfoodfacts.org:rpool zfs-hdd/off-backups/scaleway-03/rpool

