
# I will first make some of those copies manually (hence why they are commented for now)

# --no-sync-snap --no-privilege-elevation --recursive scaleway01operator@off1.openfoodfacts.org:zfs-hdd/obf zfs-hdd/backups/off1-zfs-hdd/obf
# --no-sync-snap --no-privilege-elevation --recursive scaleway01operator@off1.openfoodfacts.org:zfs-hdd/off zfs-hdd/backups/off1-zfs-hdd/off
# --no-sync-snap --no-privilege-elevation --recursive scaleway01operator@off1.openfoodfacts.org:zfs-hdd/off-nvme zfs-hdd/backups/off1-zfs-hdd/off-nvme
# --no-sync-snap --no-privilege-elevation --recursive scaleway01operator@off1.openfoodfacts.org:zfs-hdd/off-pro zfs-hdd/backups/off1-zfs-hdd/off-pro
# --no-sync-snap --no-privilege-elevation --recursive scaleway01operator@off1.openfoodfacts.org:zfs-hdd/off-pro-nvme zfs-hdd/backups/off1-zfs-hdd/off-pro-nvme
# --no-sync-snap --no-privilege-elevation --recursive scaleway01operator@off1.openfoodfacts.org:zfs-hdd/opf zfs-hdd/backups/off1-zfs-hdd/opf
# --no-sync-snap --no-privilege-elevation --recursive scaleway01operator@off1.openfoodfacts.org:zfs-hdd/opff zfs-hdd/backups/off1-zfs-hdd/opff
# --no-sync-snap --no-privilege-elevation --recursive scaleway01operator@off1.openfoodfacts.org:zfs-hdd/pve zfs-hdd/backups/off1-zfs-hdd/pve

# --no-sync-snap --no-privilege-elevation --recursive scaleway01operator@off1.openfoodfacts.org:zfs-nvme/pve zfs-hdd/backups/off1-zfs-nvme/pve

# Note: zfs-hdd/backups and zfs-hdd/off-backups are intentionally omitted.
