
- name: Compute links to create / remove and conflicts
  ansible.builtin.set_fact:
    _symlinks: "{{ '/etc/nginx' | git_based_config_symlink_check(reverse_proxy_nginx__nginx_git_config_path) }}"


- Create symlinks
  ansible.builtin.file:
    src: '{{ item.src }}'
    dest: /etc/nginx/{{ item.path }}
    state: link
    follow: false  # avoid corrupting target files if the link already exists
    force: true
  loop: "{{ community.general.filetree(reverse_proxy_nginx__nginx_git_config_path) | filter }}"
  when: item.state == 'link'

- name: Link configs files from git repo
  ansible.builtin.file:
    path: /etc/sanoid/sanoid.conf
    state: link
    src: "{{ sanoid__configurations_git_root_path }}/{{ sanoid__configurations_src_path }}/sanoid/sanoid.conf"
  when: sanoid__link_configuration