---
- name: Add the nginx apt repository to get latest updates
  ansible.builtin.deb822_repository:
    allow_insecure: false
    components: nginx
    name: nginx
    uris: https://nginx.org/packages/mainline/debian
    suites: "{{ ansible_facts['lsb'].codename }}"
    trusted: true
    enabled: true
    signed_by: https://nginx.org/keys/nginx_signing.key

- name: Install nginx and certbot from distribution
  ansible.builtin.apt:
    pkg:
      - nginx
      - python3-certbot-nginx
    state: present
    update_cache: true

# adopt debian pattern
- name: Ensure sites-enabled directory exists
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Add conf file for sites-enabled inclusion
  ansible.builtin.copy:
    # use zz- prefix to ensure it's the last to be loaded
    dest: /etc/nginx/conf.d/zz-sites-enabled.conf
    content: |
      # WARNING: handled by ansible, do not change manually
      # Include all config files from sites-enabled directory
      include /etc/nginx/sites-enabled/*;
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reverse_proxy_nginx__reload_nginx

# base debian and nginx mainline does not use the same user
- name: Ensure permissions swap from www-data to nginx
  ansible.builtin.command:
    # we also have /dev/shm because it is common to have cache there
    cmd: chown nginx -v --from www-data -R /var/cache/nginx /var/www /dev/shm
  register: _reverse_proxy_nginx__chown
  changed_when: "'changed ownership' in _reverse_proxy_nginx__chown.stdout"

- name: Install certbot ovh dns plugin
  ansible.builtin.import_tasks:
    file: certbot_ovh_dns.yml
  when: reverse_proxy_nginx__certbot_ovh_install

- name: Install prometheus exporter
  ansible.builtin.import_tasks:
    file: prometheus_exporter.yml
  when: reverse_proxy_nginx__install_prometheus

- name: Update repository to have recent configuration files
  ansible.builtin.include_role:
    name: git_based_configs
    tasks_from: repository_update
  vars:
    git_based_configs__repository_dest: "{{ reverse_proxy_nginx__nginx_git_root_path }}"

- name: Remove default site
  ansible.builtin.file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent

- name: Link config files
  git_based_config_symlinks:
    src: "{{ reverse_proxy_nginx__nginx_git_config_path }}"
    dst: "/etc/nginx"
  notify:
    - Reverse_proxy_nginx__reload_nginx
