---
- name: Install prometheus nginx exporter from distribution
  ansible.builtin.apt:
    pkg:
      - prometheus-nginx-exporter
    state: present

- name: Ensure stub_status is available on 8080
  ansible.builtin.copy:
    dest: /etc/nginx/sites-enabled/stub_status
    src: stub_status
    mode: "0644"
  notify:
    - Reverse_proxy_nginx__reload_nginx
