---
docker__volumes_virtiofs: "qm-{{ proxmox_vm_id }}-virtiofs-docker-volumes"
continuous_deployment__ssh_public_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIITFwDowPxN/XGvO015AEq9Bg3rcIzBiDdwQqcthfCpN off@off-keycloak-org"
