# token to access github.
# Must have rights to create deploy keys on infrastructure repository
# Currently it means a classic token, with public_repo access
git_based_configs__github_token: ""
# path where you want to clone the repository
git_based_configs__repository_dest: ""
# name of the repository
git_based_configs__repository_name: "openfoodfacts-infrastructure"
# owner of the repository
git_based_configs__repository_owner: "openfoodfacts"
# is the repository read only ?
# It should be true for most deploy repositories
git_based_configs__read_only_repository: true
# which users own the local repository
git_based_configs__user: "root"

# Optional

# branch to use, if not defined, we will use the same branch as local branch name
git_based_configs__branch: null
# force branch switch, on distant server (instead of asking confirmation)
git_based_configs__force_branch_switch: false
