---
- name: 'Check mandatory variables are defined'
  ansible.builtin.assert:
    that:
      - git_based_configs__github_token
      - git_based_configs__repository_dest

- name: Install git
  ansible.builtin.package:
    name: git
    state: present

- name: Create the deploy key for the server in the repository
  community.crypto.openssh_keypair:
    path: /root/.ssh/id_rsa
    mode: '0600'
    type: ed25519
    force: false
    comment: "root@{{ ansible_hostname }}"

- name: Fetch public key content
  ansible.builtin.slurp:
    src: /root/.ssh/id_rsa.pub
  register: _ssh_key_public

- name: Add the key on github
  community.general.github_deploy_key:
    # slurp encode in base64, so we have to decode
    key: "{{ _ssh_key_public.content | ansible.builtin.b64decode }}"
    read_only: false  # we want to be able to push changes
    name: "{{ ansible_hostname }} deploy key"
    owner: "{{ git_based_configs__repository_owner }}"
    repo: "{{ git_based_configs__repository_name }}"
    token: "{{ git_based_configs__github_token }}"
    state: present
  register: _github_deploy_key_result

- name: Clone the repository in /opt
  ansible.builtin.git:  # noqa: latest
    repo: "git@github.com:{{ git_based_configs__repository_owner }}/{{ git_based_configs__repository_name }}.git"
    dest: "{{ git_based_configs__repository_dest }}"
    update: false
    accept_newhostkey: true


# this is important because most of the time we directly work on develop
# with local changes and remote changes, but we want to keep a linear history
- name: Ensure we do pull --rebase by default
  community.general.git_config:
    name: pull.rebase
    value: true
    scope: global
