---
galaxy_info:
  author: teleboas
  description: Base configuration for all servers
  company: openfoodfacts

  license: MIT

  min_ansible_version: "6.1"

  platforms:
    - name: Debian
      versions:
        - stretch # Debian 9
        - buster # Debian 10
        - bullseye # Debian 11
        - bookworm # Debian 12

dependencies: []
