# pulling from scaleway-05
# scaleway-05 rpool backups
--no-sync-snap --no-privilege-elevation --recursive scaleway04operator@10.13.0.5:rpool zfs-hdd/off-backups/scaleway-05-rpool
# scaleway-05 pve backups
--no-sync-snap --no-privilege-elevation --recursive scaleway04operator@10.13.0.5:zfs-hdd/pve zfs-hdd/off-backups/scaleway-05-pve
--no-sync-snap --no-privilege-elevation --recursive scaleway04operator@10.13.0.5:zfs-nvme/pve zfs-hdd/off-backups/scaleway-05-pve-nvme
