# Setting up vlan corresponding to a vswitch
---
- name: Check variables
  ansible.builtin.assert:
    that:
      - hetzner_vswitch__vlan_id is not none
      - hetzner_vswitch__interface is not none
      - hetzner_vswitch__bridge_name is not none
      # we should not include vlan in interface name
      - "'.' not in hetzner_vswitch__interface"
      - (hetzner_vswitch__ip_address is not none) or (hetzner_vswitch__ip6_address is not none)
    fail_msg: "One of the variables is not set or wrongly set"

- name: Create the network config file
  ansible.builtin.template:
    src: vswitch_interface.j2
    dest: /etc/network/interfaces.d/vswitch-{{ hetzner_vswitch__vlan_id }}
    mode: "0644"
    owner: root
    group: root
  notify:
    - "Hetzner_vswitch : restart vswitch"
