---
- name: Install mailx, used by email-failures
  ansible.builtin.package:
    name: bsd-mailx
    state: present

- name: Add email-failures service definition
  ansible.builtin.copy:
    src: email-failures@.service
    dest: /etc/systemd/system/email-failures@.service
    mode: "0644"
  register: _systemd_email_failures__definition

- name: Reload systemd if needed.
  ansible.builtin.systemd_service:
    # reload systemd daemon the before applying changes
    daemon_reload: true
  when: _systemd_email_failures__definition.changed
