---
# the cluster name
proxmox_node__pve_cluster_enabled: false
# It must correspond to a group of nodes in inventory, with corresponding group_vars variables
# Note: proxmox validate cluster name a regex, it can only contains "-" not "_"
# https://github.com/proxmox/pve-common/blob/85d46b41030f538e1e42b570187b0aea3f3f6afd/src/PVE/JSONSchema.pm#L256
# This must be set if proxmox_node__pve_cluster_enabled is true
proxmox_node__pve_cluster_name: null

# addr
proxmox_node__pve_cluster_addr0: null
proxmox_node__pve_cluster_addr1: null

# correspond to pve_storages in lae.proxmox
proxmox_node__pve_storages: []
# correspond to pve_acls in lae.proxmox
proxmox_node__pve_acls: []
# correspond to pve_groups in lae.proxmox
proxmox_node__pve_groups: []
# correspond to pve_users in lae.proxmox
proxmox_node__pve_users: []


# the partitions you want to create or remove
# use this to create partitions for you zpool if needed
proxmox_node_partitions: []

# the zfs pools you want to create or remove
proxmox_node_zfs_pools: []
# supported keys, see https://github.com/aisbergg/ansible-role-zfs
# for example:
#  - name: hdd-zfs
#    vdev: raidz1 sda5 sdb5 sdc5 sdd5 cache nvme0n1 nvme1n1
#    extra_create_options:
#      ashift: "12"
#    filesystem_properties:
#      compress:on
#      xattr:sa
#      atime:off
#      relatime:on

# the filesystems you want to create or remove
# normally you should use this for zfs datasets that are necessary for the system
# not the one managed by proxmox, like containers or virtual machines
proxmox_node_zfs_filesystems: []
# supported keys, see https://github.com/aisbergg/ansible-role-zfs
proxmox_node_zfs_volumes: []
# supported keys, see https://github.com/aisbergg/ansible-role-zfs

proxmox_node_alerts_email: ''

# should we create the partitions or just check if they are there?
# NOTE: the idea is to set that manually to true on the command line,
# when you want to create the partitions
# -e "proxomox_node_mkparts=true"
proxomox_node_mkparts: false
