search openstreetmap.fr
# FDN no more available
# TCP is required (udp does not seems to work)
options use-vc
nameserver 2001:910:800::12
# dns0.eu
nameserver 2a0f:fc80::
nameserver 2a0f:fc81::
#nameserver 192.168.10.1
