---
- name: Fail if 'continuous_deployment__ssh_public_keys' is not defined or empty
  ansible.builtin.fail:
    msg: "The variable 'continuous_deployment__ssh_public_keys' must be defined, not empty"
  when: continuous_deployment__ssh_public_keys is not defined or continuous_deployment__ssh_public_keys | length == 0

- name: Create linux user for deployer
  ansible.builtin.user:
    name: "{{ continuous_deployment__user }}"
    comment: "User used by the GitHub Actions to deploy"
    append: true
    groups: docker # append the docker group to the user, to allow docker commands
    state: present
    create_home: true
    shell: /bin/bash
    password: "*" # ie no password / no login

- name: Ensures all SSH public keys are present for deployers
  ansible.posix.authorized_key:
    user: "{{ continuous_deployment__user }}"
    key: "{{ continuous_deployment__ssh_public_keys | join('\n') }}"
    exclusive: true # remove all other non-specified keys from the authorized_keys file

- name: Create linux user for deployers on jump proxy
  ansible.builtin.user:
    name: "{{ continuous_deployment__user }}"
    comment: "User used by the GitHub Actions to deploy"
    state: present
    create_home: true
    shell: /usr/sbin/nologin
    password: "!" # ie no password / no login
  delegate_to: "{{ continuous_deployment__proxy_jump_host or 'localhost' }}"
  when: (continuous_deployment__proxy_jump_host | default(false)) is truthy

- name: Ensures all SSH public keys are present for deployers on jump proxy
  ansible.posix.authorized_key:
    user: "{{ continuous_deployment__user }}"
    key: "{{ continuous_deployment__ssh_public_keys | join('\n') }}"
    exclusive: false # there might be other proxy jump needed
  delegate_to: "{{ continuous_deployment__proxy_jump_host or 'localhost' }}"
  when: (continuous_deployment__proxy_jump_host | default(false)) is truthy
