# {{ ansible_managed }}

dns_ovh_endpoint = {{ reverse_proxy_docker__certbot_ovh_endpoint }}
dns_ovh_application_key = {{ reverse_proxy_docker__certbot_ovh_application_key }}
dns_ovh_application_secret = {{ reverse_proxy_docker__certbot_ovh_application_secret }}
dns_ovh_consumer_key = {{ reverse_proxy_docker__certbot_ovh_consumer_key }}
