#! /bin/bash

# Script de création de compte avec clé SSH github

read -p 'desired username in container/VM: ' U
read -p 'github username (to get public SSH key): ' GU

useradd $U -m -s /usr/sbin/nologin
mkdir -p /home/$U/.ssh
curl -sL "https://github.com/$GU.keys" > /home/$U/.ssh/authorized_keys
chown $U:$U -R /home/$U/.ssh
chmod 400 /home/$U/.ssh/authorized_keys


read -p 'which container/VM ID (100.., 200..): ' CT

if [ "$CT" -lt "200" ]
then
lxc-attach -n $CT -- useradd $U -m -s /bin/bash
lxc-attach -n $CT -- mkdir -p /home/$U/.ssh
lxc-attach -n $CT -- wget -q "https://github.com/$GU.keys"
lxc-attach -n $CT -- mv $GU.keys /home/$U/.ssh/authorized_keys
lxc-attach -n $CT -- chown $U:$U -R /home/$U/.ssh
lxc-attach -n $CT -- chmod 400 /home/$U/.ssh/authorized_keys
lxc-attach -n $CT -- usermod -a -G sudo $U
else
qm guest exec $CT -- useradd $U -m -s /bin/bash
qm guest exec $CT -- mkdir -p /home/$U/.ssh
qm guest exec $CT -- wget -q "https://github.com/$GU.keys"
qm guest exec $CT -- mv $GU.keys /home/$U/.ssh/authorized_keys
qm guest exec $CT -- chown $U:$U -R /home/$U/.ssh
qm guest exec $CT -- chmod 400 /home/$U/.ssh/authorized_keys
qm guest exec $CT -- usermod -a -G sudo $U
fi
