---
galaxy_info:
  author: teleboas
  description: sshd tuning with user and authorized keys management
  company: openfoodfacts

  license: MIT

  min_ansible_version: "6.1"

  platforms:
    - name: Debian
      versions:
        - stretch # Debian 9
        - buster # Debian 10
        - bullseye # Debian 11
        - bookworm # Debian 12

# TODO: remove we run it also in tasks
dependencies:
  - willshersystems.sshd
