[hdd-zfs]
  use_template=local_data
  recursive=yes

[data-zfs]
  use_template=local_data
  recursive=yes

[data-zfs/docker-volumes/monitoring_elasticsearch-data]
  use_template=fast_moving_data

[hdd-zfs/monitoring-es-backups]
  use_template=fast_moving_data

# Template to regularly snapshot
[template_local_data]
  # How often snapshots should be taken under an hour
  frequent_period=30
  # What to keep
  # number of sub-hourly snapshots
  frequently = 0
  # number of hourly snapshots
  hourly = 36
  # number of daily snashots
  daily = 30
  # number of monthly snashots
  monthly = 6
  # number of yearly snashots
  yearly = 0
  # whether snapshots should be taken automatically
  autosnap = yes
  # Should old snapshots be pruned
  autoprune = yes

# Template for ES data, which change a lot and we have backups
# so we keep fewer snapshots
[template_fast_moving_data]
  # How often snapshots should be taken under an hour
  frequent_period=30
  # What to keep
  # number of sub-hourly snapshots
  frequently = 0
  # number of hourly snapshots
  hourly = 36
  # number of daily snashots
  daily = 6
  # number of monthly snashots
  monthly = 2
  # number of yearly snashots
  yearly = 0
  # whether snapshots should be taken automatically
  autosnap = yes
  # Should old snapshots be pruned
  autoprune = yes

