reverse_proxy_websites:
  - url: "monitoring.off.epy.ovh"
    proxy_pass: "example-webserver:80"
  - url: "tartelette.off.epy.ovh"
    proxy_pass: "example-webserver:80"
  - url: "pomme.off.epy.ovh"
    proxy_pass: "example-webserver:80"

  
reverse_proxy_https_domain: "off.epy.ovh"
reverse_proxy_https_email: ""