---
reverse_proxy_docker__websites:
  - url: "alertmanager.openfoodfacts.org"
    proxy_pass: "alertmanager:9093"
    username: "off"
    password: "{{ password_monitoring_sites }}"

  - url: "prometheus.openfoodfacts.org"
    proxy_pass: "prometheus:9090"
    username: "off"
    password: "{{ password_monitoring_sites }}"
    public_paths:
      # enable external monitoring of prometheus state !
      - "/-/healthy"

  - url: "monitoring.openfoodfacts.org"
    proxy_pass: "grafana:3000"

  - url: "grafana.openfoodfacts.org"
    proxy_pass: "grafana:3000"

  - url: "elasticsearch.openfoodfacts.org"
    proxy_pass: "elasticsearch:9200"
    username: "off"
    password: "{{ password_monitoring_elasticsearch }}"

  - url: "kibana.openfoodfacts.org"
    proxy_pass: "kibana:5601"
    username: "off"
    password: "{{ password_monitoring_elasticsearch }}"
