map $uri $beta_off_net_basic_auth_setting {
  default "login off/off - to avoid crawling";
  # whitelist health
  /health "";
}

server {
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/beta.openfoodfacts.net/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/beta.openfoodfacts.net/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    server_name  beta.openfoodfacts.net;

    http2 on;
    
    # off:off basic username to avoid indexation by bots (it's staging env)
    auth_basic_user_file /etc/nginx/off.htpasswd;
    # require authentication so that it is not crawled by robots
    auth_basic $beta_off_net_basic_auth_setting;

    # Enable gzip
    gzip on;
    # Required for proxies to pass the correct headers to the backend
    gzip_vary on;
    gzip_proxied any;

    gzip_min_length 256;
    gzip_types
        text/plain
        text/css
        text/javascript
        application/javascript
        application/json
        application/xml
        image/svg+xml;
    
    access_log  /var/log/nginx/off_explorer.access.log  main;

    location / {

	# Increase proxy buffers to handle large headers from the backend
        proxy_buffer_size           128k;
        proxy_buffers               4 256k;
        proxy_busy_buffers_size     256k;
	# explorer is deployed on staging dockers
        proxy_pass          http://10.1.0.200:3000;
        proxy_set_header    Host $host;
	proxy_set_header    X-Real-IP $remote_addr;
	proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header    X-Forwarded-Proto $scheme;
    }
}

server {
    if ($host = beta.openfoodfacts.net) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name beta.openfoodfacts.net;

    listen 80;
}
