# https redirect
server {
    if ($host = ovh-exporters.openfoodfacts.org) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    listen [::]:80;
    server_name ovh-exporters.openfoodfacts.org;

    location /.well-known {
        root /var/www/html;
        try_files $uri =404;
    }
    return 404;
}


# map from service to exporter
# We follow the schema job/env/app/service
map $uri $exporter {

    # new style using exporter_exporter
    # exporter_exporter for scaleway-docker-prod
    "~/ovh-docker-staging" 10.1.0.200:8202;
    "~/ovh-docker-prod" 10.1.0.201:8202;

    # other direct access exporters
    # TODO: we should use exporter_exporter there also
    # Proxmox gateway postfix
    "/pmg-postfix/prod/pmg/postfix/metrics" 10.1.0.102:9154;
    # matomo mysqld
    "/mysqld/prod/matomo/mysqld/metrics" 10.1.0.107:9104;
    # matomo nginx
    "/mysqld/prod/matomo/nginx/metrics" 10.1.0.107:9113;
}

#log_format debug_exporter "$time_local $scheme://$host:$server_port$request_uri $exporter";

# https server
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name ovh-exporters.openfoodfacts.org;

    # SSL/TLS settings
    ssl_certificate /etc/letsencrypt/live/ovh-exporters.openfoodfacts.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ovh-exporters.openfoodfacts.org/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/ovh-exporters.openfoodfacts.org/chain.pem;

    # logs location, avoid access_log, no need
    #access_log  /var/log/nginx/ovh-exporters.log  debug_exporter;
    #access_log  /var/log/nginx/ovh-exporters.log  main;
    access_log  off;
    error_log   /var/log/nginx/ovh-exporters.errors.log;

    # protect
    auth_basic "Exporter metrics";
    auth_basic_user_file "/etc/nginx/.htpasswd/ovh-exporters";

    # new style config - we use the fact tha subpath as no "/" in it to differentiate
    location ~ ^/[^/]+/(?<subpath>[^/]+)?$ {
        if ($exporter = "") {
            return 404;
        }
	proxy_pass http://$exporter/$subpath$is_args$args;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto https;
	proxy_set_header Host $host;
	client_max_body_size 512M;
    }

    # old style config
    # url to join is defined thanks to exporter variable, itself based upon uri
    location / {

        if ($exporter = "") {
            return 404;
        }
        proxy_pass http://$exporter/metrics;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Host $host;
        client_max_body_size 512M;
    }
}



