server {
    listen 443;
    listen [::]:443;
    server_name  recipe-estimator.openfoodfacts.org;

    access_log  /var/log/nginx/recipe-estimator.off.org.log  main;
    error_log   /var/log/nginx/recipe-estimator.off.org.errors.log;

    location / {
        proxy_pass http://10.1.0.201:5520$request_uri;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 90;
        client_max_body_size 512M;
    }


    ssl_certificate /etc/letsencrypt/live/recipe-estimator.openfoodfacts.org/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/recipe-estimator.openfoodfacts.org/privkey.pem; # managed by Certbot
}

server {
    if ($host = recipe-estimator.openfoodfacts.org) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


  listen 80;
  listen [::]:80;
  server_name  recipe-estimator.openfoodfacts.org;

}


