map $uri $recipes_off_net_basic_auth_setting {
  default "login off/off - to avoid crawling";
  # whitelist health
  /health "";
}

# api server
server {

    server_name  api.recipes.openfoodfacts.net;
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/api.recipes.openfoodfacts.net/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/api.recipes.openfoodfacts.net/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
    
    http2 on;
    
    access_log  /var/log/nginx/api.recipes.off.net.log  main;
    error_log   /var/log/nginx/api.recipes.off.net.errors.log;

    # Enable gzip
    gzip on;
    # Required for proxies to pass the correct headers to the backend
    gzip_vary on;
    gzip_proxied any;
    gzip_min_length 256;
    gzip_types
        text/plain
        text/css
        text/javascript
        application/javascript
        application/json
        application/xml
        image/svg+xml;
    

    location / {
        proxy_pass http://10.1.0.200:5750;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 90;
        client_max_body_size 512M;
    }



}
    
server {

    server_name  recipes.openfoodfacts.net ui.recipes.openfoodfacts.net;
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/ui.recipes.openfoodfacts.net/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/ui.recipes.openfoodfacts.net/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
    
    http2 on;
   
    # 2026/08/05 - removing authentication to ease testing (even if it's staging) 
    # off:off basic username to avoid indexation by bots (it's staging env)
    # auth_basic_user_file /etc/nginx/off.htpasswd;
    # require authentication so that it is not crawled by robots
    # auth_basic $recipes_off_net_basic_auth_setting;

    # redirect recipes to ui.recipes
    if ($host = recipes.openfoodfacts.net) {
        return 301 https://ui.$host$request_uri;
    } 

    access_log  /var/log/nginx/ui.recipes.off.net.log  main;
    error_log   /var/log/nginx/ui.recipes.off.net.errors.log;

    # Enable gzip
    gzip on;
    # Required for proxies to pass the correct headers to the backend
    gzip_vary on;
    gzip_proxied any;
    gzip_min_length 256;
    gzip_types
        text/plain
        text/css
        text/javascript
        application/javascript
        application/json
        application/xml
        image/svg+xml;
    
    location / {
	# Increase proxy buffers to handle large headers from the backend
        proxy_buffer_size           128k;
        proxy_buffers               4 256k;
        proxy_busy_buffers_size     256k;
        # pass to svelte
        proxy_pass http://10.1.0.200:5751;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 90;
        client_max_body_size 512M;
    }

}

server {
  if ($host = recipes.openfoodfacts.net) {
    return 301 https://$host$request_uri;
  } # managed by Certbot
  if ($host = ui.recipes.openfoodfacts.net) {
    return 301 https://$host$request_uri;
  } # managed by Certbot
  if ($host = api.recipes.openfoodfacts.net) {
    return 301 https://$host$request_uri;
  } # managed by Certbot

  listen 80;
  server_name  recipes.openfoodfacts.net ui.recipes.openfoodfacts.net api.recipes.openfoodfacts.net;
}
