
server {

    server_name  taxonomies.openfoodfacts.net;
    listen [::]:443 ssl;
    listen 443 ssl;
    http2 on;

    gzip on;
    gzip_min_length 1000;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript text/csv;
    gzip_static always;

    ssl_certificate /etc/letsencrypt/live/taxonomies.openfoodfacts.net/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/taxonomies.openfoodfacts.net/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

 
    access_log  /var/log/nginx/taxonomies.off.net.log  main;
    error_log   /var/log/nginx/taxonomies.off.net.errors.log;

    location = / {
        return 301 "https://$host/showvoc#/datasets";
    }

    location / {
        proxy_pass http://10.1.0.200:1983$request_uri;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 90;
        client_max_body_size 512M;
    }

}

server {
    listen 80;
    listen [::]:80;
    if ($host = taxonomies.openfoodfacts.net) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

}
