# off1 backups
--no-sync-snap --no-privilege-elevation --recursive scaleway02operator@off1.openfoodfacts.org:zfs-hdd/pve zfs-hdd/off-backups/off1-zfs-hdd/pve
--no-sync-snap --no-privilege-elevation --recursive scaleway02operator@off1.openfoodfacts.org:zfs-nvme/pve zfs-hdd/off-backups/off1-zfs-nvme/pve
# Note: zfs-hdd/backups and zfs-hdd/off-backups are intentionally omitted.

# some specific off2 backups we need here (redis and postgres data)
--no-sync-snap --no-privilege-elevation  scaleway02operator@off2.openfoodfacts.org:zfs-hdd/pve/subvol-122-disk-1 zfs-hdd/off-backups/off2-zfs-hdd/pve/subvol-122-disk-1
--no-sync-snap --no-privilege-elevation  scaleway02operator@off2.openfoodfacts.org:zfs-nvme/pve/subvol-120-disk-0 zfs-hdd/off-backups/off2-zfs-nvme/pve/subvol-120-disk-0

# we cross backup rpool of scaleway cluster
--no-sync-snap --no-privilege-elevation --recursive scaleway02operator@scaleway-01.infra.openfoodfacts.org:rpool zfs-hdd/off-backups/scaleway-01/rpool
--no-sync-snap --no-privilege-elevation --recursive scaleway02operator@scaleway-03.infra.openfoodfacts.org:rpool zfs-hdd/off-backups/scaleway-03/rpool

