
# I will first make some of those copies manually (hence why they are commented for now)

--no-sync-snap --no-privilege-elevation --recursive scaleway02operator@off1.openfoodfacts.org:zfs-hdd/pve zfs-hdd/off-backups/off1-zfs-hdd/pve

--no-sync-snap --no-privilege-elevation --recursive scaleway02operator@off1.openfoodfacts.org:zfs-nvme/pve zfs-hdd/off-backups/off1-zfs-nvme/pve

# Note: zfs-hdd/backups and zfs-hdd/off-backups are intentionally omitted.
