
# map from service to exporter
map $uri $exporter {
    # exporter_exporter for scaleway-docker-prod
    "~/scaleway-docker-prod" 10.13.1.200:8202;
}

#log_format debug_exporter "$time_local $scheme://$host:$server_port$request_uri $exporter";

# http server
server {
    server_name scaleway-exporters.openfoodfacts.org;

    # logs location, avoid access_log, no need
    #access_log  /var/log/nginx/scaleway-exporters.log  debug_exporter;
    #access_log  /var/log/nginx/scaleway-exporters.log  main;
    access_log  off;
    error_log   /var/log/nginx/scaleway-exporters.errors.log;

    # protect
    auth_basic "Exporter metrics";
    auth_basic_user_file "/etc/nginx/.htpasswd/scaleway-exporters";

    # url to join is defined thanks to exporter variable, itself based upon uri
    location ~^/[^/]+/(?<subpath>.+)?$ {
        if ($exporter = "") {
            return 404;
        }
	proxy_pass http://$exporter/$subpath$is_args$args;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto https;
	proxy_set_header Host $host;
	client_max_body_size 512M;
    }

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/scaleway-exporters.openfoodfacts.org/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/scaleway-exporters.openfoodfacts.org/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}




server {
    if ($host = scaleway-exporters.openfoodfacts.org) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;
    server_name scaleway-exporters.openfoodfacts.org;
    return 404; # managed by Certbot


}
