---
proxmox_node__pve_cluster_addr0: 10.13.0.3

# ZFS pools were created manually. We keep them out of Ansible as they might be modified manually.
proxmox_node__zfs_pools: []
proxmox_node__zfs_filesystems: "{{ pvescaleway_common_proxmox_node__zfs_filesystems }}"
