---
- name: Ensure docker volumes exists, in case we want to mount from virtiofs
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: root
    group: root
  when: "docker__volumes_virtiofs | default(False)"
  loop:
    - path: "/var/lib/docker"
      mode: "0710"
    - path: "/var/lib/docker/volumes"
      mode: "0701"

- name: Eventually mount docker volumes from virtiofs
  ansible.builtin.import_role:
    name: virtiofs_mounts
  vars:
    virtiofs_mounts__mounts:
      - src: "{{ docker__volumes_virtiofs }}"
        path: "/var/lib/docker/volumes"
        state: "{{ 'mounted' if (docker__volumes_virtiofs is defined) else 'absent' }}"
  when: "docker__volumes_virtiofs | default(False)"

- name: Install docker
  ansible.builtin.import_role:
    name: geerlingguy.docker

- name: Make ansible user part of docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    append: true
    groups: docker

- name: Copy docker daemon config
  ansible.builtin.copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: "0644"
  # restart docker if the config file changed
  notify: Restart docker
