# Declare all servers here with their configuration variables
# Please sort it alphabetically

[all:vars]
ansible_ssh_user=config-op
host_domain=infra.openfoodfacts.org
ansible_host='{{ inventory_hostname }}.{{ host_domain }}'

# 1. containers have a proxmox_node variable that we should use to ssh jump
# 2. establish a tunnel to be able to join the API from localhost
#    Each host must have it's own proxmox_api_local_port to avoid conflicts
ansible_ssh_common_args = '{{ "-J " ~ hostvars[proxmox_node]["ansible_ssh_host"] if (proxmox_node|default(false)) else "" }} {{ ("-L " ~ proxmox_api_local_port ~ ":127.0.0.1:8006") if (proxmox_api_local_port|default(false)) else "" }}'

[monitoring]
monitoring-01 ansible_ssh_host=34.1.5.157 ansible_ssh_user=debian

# host that are not fully managed by ansible
[non_ansible_hosts]
off1 ansible_ssh_host=213.36.253.206
off2 ansible_ssh_host=213.36.253.208 extra_host_ips="2a01:e0d:1:c:58bf:fad0:0:1"
proxy_off1 ansible_ssh_host=213.36.253.215
proxy_off2 ansible_ssh_host=213.36.253.214
ovh1 ansible_ssh_host=146.59.148.140 extra_host_ips="2001:41d0:203:948c::1"
proxy_ovh1 ansible_ssh_host=46.105.72.120 extra_host_ips="2001:41d0:203:948c::101"
ovh2 ansible_ssh_host=51.210.154.203
ovh3 ansible_ssh_host=51.210.32.79
ks1 ansible_ssh_host=217.182.132.133
osm_proxy_host ansible_ssh_host=217.182.132.133
osm45 ansible_ssh_host="2a06:c484:5::102"
folksonomy

[proxmox_nodes]
off1 ansible_ssh_host=213.36.253.206
off2 ansible_ssh_host=213.36.253.208
ovh1 ansible_ssh_host=146.59.148.140 extra_host_ips="2001:41d0:203:948c::1"
ovh2 ansible_ssh_host=51.210.154.203 extra_host_ips="2001:41d0:403:41cb::2"
ovh3 ansible_ssh_host=51.210.32.79
# backup server
hetzner-01 ansible_ssh_host=49.12.168.77 extra_host_ips="2a01:4f8:2190:1498::2" proxmox_api_local_port=8101
# compute server
hetzner-02 ansible_ssh_host=88.99.90.100 extra_host_ips="2a01:4f8:10a:1a95::2" proxmox_api_local_port=8102
hetzner-03 ansible_ssh_host=195.201.104.92 extra_host_ips="2a01:4f8:13a:a2::2" proxmox_api_local_port=8103
scaleway-01 ansible_ssh_host=151.115.132.11 extra_host_ips="2001:bc8:c025:11::" proxmox_api_local_port=8111
scaleway-02 ansible_ssh_host=151.115.132.12 extra_host_ips="2001:bc8:c025:12::" proxmox_api_local_port=8112
scaleway-03 ansible_ssh_host=151.115.132.13 extra_host_ips="2001:bc8:c025:13::" proxmox_api_local_port=8113

[hetzner_containers]
hetzner-02-proxy ansible_ssh_host=10.12.1.100 proxmox_node="hetzner-02"
folksonomy-staging ansible_ssh_host=10.12.1.110 proxmox_node="hetzner-02"
superset ansible_ssh_host=10.12.1.111 proxmox_node="hetzner-02"

[ovh_containers]
folksonomy ansible_ssh_host=10.1.0.108 proxmox_node="ovh1"

[containers:children]
ovh_containers
hetzner_containers

[reverse_proxy_hosts]
hetzner-02-proxy

[pve_hetzner]
hetzner-01
hetzner-02
hetzner-03

[pve_scaleway]
scaleway-01
scaleway-02
scaleway-03

[standalone_servers]
# servers that are not proxmox nodes but are standalone servers
monitoring-01
ks1