---
collections:
  - name: community.general
    version: 11.2.1
  - name: community.crypto
    version: 2.22.3
  - name: community.docker
    version: 4.5.2
  - name: community.proxmox
    version: 1.3.0

roles:
  - src: willshersystems.sshd
    version: v0.28.0
  - src: oefenweb.fail2ban
    version: v4.0.10
  - name: lae.proxmox
    src: https://github.com/lae/ansible-role-proxmox
    # 1.10.1
    version: dbbc5ec0f718946466c89ea48428a93b548e89c3
    scm: git
  - name: aisbergg.zfs
    # patched, see https://github.com/aisbergg/ansible-role-zfs/pull/6
    src: https://github.com/alexgarel/ansible-role-zfs.git
    version: 85777d2b4312738e14d21e66ee09c39e86d20587
    scm: git
  - src: geerlingguy.docker
    version: 8.0.0
