---
collections:
  - name: community.general
    version: 11.2.1
  - name: community.crypto
    version: 2.22.3
  - name: community.docker
    version: 4.5.2
  - name: community.proxmox
    version: 1.3.0

roles:
  - src: willshersystems.sshd
    version: v0.28.0
  - src: oefenweb.fail2ban
    version: v4.0.10
  - name: lae.proxmox
    src: https://github.com/lae/ansible-role-proxmox
    version: 43df4c92447c5fe2c5d2ce54f109035e750bf59d
    scm: git
  - name: aisbergg.zfs
    src: https://github.com/aisbergg/ansible-role-zfs.git
    version: 8940f01615e1f8abf267967953e4f67eb1b27d52
    scm: git
  - src: geerlingguy.docker
    version: 7.4.7
