# Defaults variables for iptables
---

# List of ports to open on the public interface (except docker containers)
iptables_public_ports: [22]
# List of ports to open only to our servers (except docker containers)
iptables_internal_hosts_only_ports: []
# List of docker ports to open on the public interface
iptables_public_docker_ports: []
# List of docker ports to open only to our servers
iptables_internal_hosts_only_docker_ports: []
# Our hosts that have access to special ports (also for docker containers)
iptables_internal_hosts_ips_v4: []
iptables_internal_hosts_ips_v6: []
# List of private networks, whitelisted
iptables_private_networks_v4: []
iptables_private_networks_v6: []
# you have to white list the accept policy
# by default only filter.input is drop
# DOCKER-USER chain is always in drop mode
iptables_accept_policy:
  filter: ["output", "forward"]
  nat: ["prerouting", "input", "output", "postrouting"]
# you can provide a list of extra rule as a dict
# where key is the comment and value is the rule
# it will be sorted by key lexical orders
iptables_extra_rules_filter_v4: {}
iptables_extra_rules_filter_v6: {}
iptables_extra_rules_nat_v4: {}
iptables_extra_rules_nat_v6: {}
# ip forwarding
iptables__enable_ip_forward_v4: false
iptables__enable_ip_forward_v6: false
