server {

    server_name  api.folksonomy.openfoodfacts.net api.folksonomy.new.openproductsfacts.net api.folksonomy.openproductsfacts.net api.folksonomy.openbeautyfacts.net api.folksonomy.openpetfoodfacts.net;

    listen 80;

    access_log  /var/log/nginx/folksonomy_api.access.log  main;

    location / {
	# FIXME: put real ip
        proxy_pass          http://10.1.0.108:8000;
        proxy_set_header    Host $host;
        proxy_set_header    X-Real-IP $remote_addr;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto $scheme;

    }

}
