# sanoid conf data - see https://github.com/jimsalterjrs/sanoid/wiki/Sanoid

[rpool]
  use_template=local_sys
  recursive=yes

[rpool/ROOT]
  use_template=local_sys
  recursive=yes

[rpool/data]
  use_template=local_data
  recursive=yes

[zfs-hdd]
  use_template=local_sys
  recursive=yes

[zfs-hdd/pve]
  use_template=local_sys
  recursive=yes

[zfs-hdd/off-backups]
  use_template=synced_data
  recursive=yes

[zfs-nvme]
  use_template=local_sys
  recursive=yes

[zfs-nvme/pve]
  use_template=local_sys
  recursive=yes

[template_local_data]
  frequent_period=30
  frequently = 0
  hourly = 36
  daily = 30
  monthly = 6
  yearly = 2
  autosnap = yes
  autoprune = yes

[template_local_sys]
  frequent_period=60
  frequently = 0
  hourly = 36
  daily = 10
  monthly = 6
  yearly = 0
  autosnap = yes
  autoprune = yes

[template_synced_data]
  frequently = 0
  hourly = 36
  daily = 30
  monthly = 6
  yearly = 2
  autosnap = no
  autoprune = yes