## pulling from off1

# scaleway-04 PVE managed volumes
--no-sync-snap --no-privilege-elevation --recursive scaleway-04operator@10.13.0.4:zfs-hdd/pve zfs-hdd/off-backups/off1-pve
--no-sync-snap --no-privilege-elevation --recursive scaleway-04operator@10.13.0.4:zfs-nvme/pve zfs-hdd/off-backups/off1-pve-nvme
# scaleway-04 root volume (rpool)
--no-sync-snap --no-privilege-elevation --recursive scaleway-04operator@10.13.0.4:rpool zfs-hdd/off-backups/off1-rpool



