# we only have volumes in rpool on this machine

[rpool]
  use_template=local_data
  recursive=yes

[rpool/subvol-101-disk-0]
  use_template=synced_data

[rpool/subvol-102-disk-0]
  use_template=synced_data

# Template to regularly snapshot
# we only keep VERY FEW snapshots to avoid filling disk space
# OVH3 will keep more of them
[template_local_data]
  # How often snapshots should be taken under an hour
  frequent_period=60
  # What to keep
  # number of sub-hourly snapshots
  frequently = 0
  # number of hourly snapshots
  hourly = 6
  # number of daily snashots
  daily = 1
  # number of monthly snashots
  monthly = 0
  # number of yearly snashots
  yearly = 0
  # whether snapshots should be taken automatically
  autosnap = yes
  # Should old snapshots be pruned
  autoprune = yes

# this is for synced data, has for the rest, we keep minimal snapshots
[template_synced_data]
  # How often snapshots should be taken under an hour
  frequent_period=60
  # What to keep
  # number of sub-hourly snapshots
  frequently = 0
  # number of hourly snapshots
  hourly = 6
  # number of daily snashots
  daily = 1
  # number of monthly snashots
  monthly = 0
  # number of yearly snashots
  yearly = 0
  # disable snapshots has they come from source
  autosnap = no
  # Should old snapshots be pruned
  autoprune = yes
  # remove eventual @vzdump snapshot and syncoid_ (transient snapshot on source side)
  pruning_script = /opt/openfoodfacts-infrastructure/scripts/zfs/sanoid_post_remove_synced_data_snapshots.sh
  script_timeout = 180


