# CT 101 and 102 are important and replicated locally 
# so that in case of accident we can set them up quickly
--no-privilege-elevation ovh2operator@10.0.0.1:rpool/subvol-101-disk-0 rpool/subvol-101-disk-0
--no-privilege-elevation ovh2operator@10.0.0.1:rpool/subvol-102-disk-0 rpool/subvol-102-disk-0
