---
- name: Reverse_proxy_nginx__reload_nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: Reverse_proxy_nginx__restart_fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
