---
proxmox_node__pve_cluster_addr0: 10.13.0.1

proxmox_node__zfs_pools:
  # some ZFS pools were created manually.
  # We keep them out of Ansible as they might be modified manually.
  # -name: rpool
  # -name: zfs-hdd
  - name: zfs-nvme
    properties:
      ashift: "12"
    vdev: nvme-eui.000000000000000100a0752249f51d6e-part4 nvme-eui.00000000000000007c35485224e769cf-part4
    filesystem_properties: "{{ proxmox_node__zfs_pools_filesystem_properties_defaults }}"

proxmox_node__zfs_filesystems: "{{ pvescaleway_common_proxmox_node__zfs_filesystems }}"

proxmox_node__pve_storages:
  - name: zfs-hdd-pve
    type: zfspool
    pool: zfs-hdd/pve
    content: rootdir,images
    mountpoint: /zfs-hdd/pve
    sparse: 0
    # shared: 0 # for some reason, this flag did make the setup crash
  - name: local
    type: dir
    path: /var/lib/vz
    content: vztmpl,snippets,iso
    shared: 0
  # removing installed storage
  - name: zfs-hdd
    type: zfspool
    pool: zfs-hdd
    state: absent

proxmox_containers__containers:
  - id: 100
    hostname: scaleway-proxy
    features:
      - nesting=1
    cores: 6
    memory: "{{ 3 * 1024 }}"
    netif:
      # public network
      # we put it first so that it's the default route
      net0:
        name: eth0
        ip: 151.115.132.10/27
        gw: 151.115.132.1
        ip6: "2001:bc8:c025:11:100::/48"
        gw6: "2001:bc8:c025:ffff:ffff:ffff:ffff:ff7f"
        bridge: vmbr10
      net1:
        name: eth1
        ip: 10.13.1.100/16
        # we intentionally remove the gateway
        # so that default route should be eth0
        # gw:
        bridge: vmbr10
    disk:
      storage: zfs-hdd-pve
      size: 32
    idmap: &off-containers-idmap
      - content: "u 0 100000 999"
      - content: "g 0 100000 999"
      - content: "u 1000 1000 64536"
      - content: "g 1000 1000 64536"
  - id: 111
    hostname: "off"
    features:
      - nesting=1
    cores: 50
    memory: "{{ 160 * 1024 }}"
    netif:
      net0:
        name: eth0
        ip: 10.13.1.111/16
        gw: 10.13.0.1
        bridge: vmbr10
    disk:
      storage: zfs-hdd-pve
      size: 30
    idmap: *off-containers-idmap
  - id: 112
    hostname: off-pro
    features:
      - nesting=1
    cores: 8
    memory: "{{ 32 * 1024 }}"
    netif:
      net0:
        name: eth0
        ip: 10.13.1.112/16
        gw: 10.13.0.1
        bridge: vmbr10
    disk:
      storage: zfs-hdd-pve
      size: 30
    idmap: *off-containers-idmap
  - id: 113
    hostname: obf
    features:
      - nesting=1
    cores: 6
    memory: "{{ 12 * 1024 }}"
    netif:
      net0:
        name: eth0
        ip: 10.13.1.113/16
        gw: 10.13.0.1
        bridge: vmbr10
    disk:
      storage: zfs-hdd-pve
      size: 30
    idmap: *off-containers-idmap
  - id: 114
    hostname: opf
    features:
      - nesting=1
    cores: 6
    memory: "{{ 12 * 1024 }}"
    netif:
      net0:
        name: eth0
        ip: 10.13.1.114/16
        gw: 10.13.0.1
        bridge: vmbr10
    disk:
      storage: zfs-hdd-pve
      size: 30
    idmap: *off-containers-idmap
  - id: 115
    hostname: opff
    features:
      - nesting=1
    cores: 6
    memory: "{{ 12 * 1024 }}"
    netif:
      net0:
        name: eth0
        ip: 10.13.1.115/16
        gw: 10.13.0.1
        bridge: vmbr10
    disk:
      storage: zfs-hdd-pve
      size: 30
    idmap: *off-containers-idmap
