---
# ansible/roles/<role_name> is always under ansible/, so two dirname() calls resolve ansible/ reliably.
pull_pve_configs__repository_root: "{{ lookup('ansible.builtin.env', 'OFF_INFRA_REPOSITORY_ROOT') | default((role_path | dirname | dirname), true) }}"
pull_pve_configs__pulled_confs_root: "{{ pull_pve_configs__repository_root }}/pulled_confs"
pull_pve_configs__source_dir: /etc/pve
pull_pve_configs__exclude_regexes:
  # Exclude private key files.
  - ".*\\.key$"
  - "(^|/)ssh_known_hosts$"
  - "(^|/)authorized_keys$"
  - "(^|/)shadow\\.cfg$"
  - "(^|/)token\\.cfg$"
  - "(^|/)priv(/|$)"
