version: "3.9"

services:
  grafana:
    restart: $RESTART_POLICY
    image: grafana/grafana-oss:11.2.2-security-01
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "${GRAFANA_EXPOSE:-127.0.0.1:3000}:3000"

  influx_db:
    restart: $RESTART_POLICY
    image: influxdb:2.5.1-alpine
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_ORG: "off"
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_BUCKET: "off_metrics"
      DOCKER_INFLUXDB_INIT_PASSWORD:
    volumes:
      - influx-storage:/var/lib/influxdb2
    ports:
      - "${INFLUX_EXPOSE:-127.0.0.1:8086}:8086"
    mem_limit: 5g

volumes:
  grafana-storage:
  influx-storage:
