---
#----------------------------------------------
# Generate and upload documentation (only push to main)
#----------------------------------------------

name: Generate documentation
on:
  pull_request:
    # on pull request we just want to build to see nothing is broken
    # don't filter by path because this is a mandatory step…
  push:
    branches:
      - develop

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v7
      - name: Generate documentation
        run: |
          make build_docs
      - name: Deploy documentation to Github Pages 🚀
        # we only deploy on push to main
        if: |
          github.event_name == 'push' && github.event.ref == 'refs/heads/develop'
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: gh_pages # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branc
