---
# PSK files definition
stunnel__psk_secrets: []
# the content is username:psk
# use pwgen 32 to generate psk
# - file: postgres.psk
#   content: |
#      scaleway-02: auentuaienrst

# git repostory with system config
# This is mandatory
stunnel__config_repository_root:
stunnel__config_repository_path: "{{ stunnel__config_repository_root }}/confs/{{ inventory_hostname }}"

# Set this to true if you are on a stunnel client
stunnel__ensure_no_client: true
